export type BridgeEnvironment = "webview2" | "mock";

export type BridgeRequestType =
  | "state.snapshot"
  | "config.get"
  | "config.save"
  | "processes.refresh"
  | "monitor.start"
  | "monitor.stop"
  | "reports.list"
  | "reports.open"
  | "reports.openDirectory"
  | "reports.regenerate"
  | "logs.openDirectory"
  | "diagnostics.generate"
  | "targets.get"
  | "targets.save";

export type BridgeEventType =
  | "event.status"
  | "event.error"
  | "event.processesRefreshed"
  | "event.reportsChanged"
  | "event.reportProgress"
  | "event.hostWindowChanged";

export interface BridgeRequestEnvelope<TPayload = Record<string, unknown>> {
  requestId: string;
  type: BridgeRequestType;
  payload: TPayload;
}

export interface BridgeError {
  code: string;
  message: string;
}

export interface BridgeResponseEnvelope<TPayload = unknown> {
  requestId: string;
  type: "response";
  ok: boolean;
  payload: TPayload;
  error: BridgeError | null;
}

export interface BridgeEventEnvelope<TPayload = unknown> {
  type: BridgeEventType;
  payload: TPayload;
  sentAt?: string;
}

export interface FrameScopeTargetConfig {
  Enabled: boolean;
  Name: string;
  ProcessName: string;
  SampleIntervalMs: number;
  ProcessSamplingMode: "normal" | "high-precision" | string;
  ProcessSampleIntervalMs: number;
  SlowSampleIntervalMs: number;
  OpenReportOnComplete: boolean;
}

export type FrameScopeThemeMode = "light" | "dark" | "system";
export type FrameScopeCloseWindowBehavior = "exit" | "minimize-to-tray";
export type FrameScopeVoltageProvider = "auto" | "built-in" | "disabled" | "wmi" | "sensor";

export interface FrameScopeCpuTelemetryConfig {
  CollectPerCoreFrequency: boolean;
  CollectCpuVoltage: boolean;
  PerCoreSampleIntervalMs: number;
  PerCoreVoltageSampleIntervalMs: number;
  VoltageProvider: FrameScopeVoltageProvider;
}

export interface FrameScopeConfig {
  PollIntervalMs: number;
  TelemetrySampleIntervalMs: number;
  DataRoot: string;
  OpenReportOnComplete: boolean;
  EnableVerboseLogs: boolean;
  EnablePerformanceDiagnosticsLogs: boolean;
  AutoGenerateDiagnosticReport: boolean;
  LogRetentionDays: number;
  MaxLogDiskMb: number;
  MonitorScript: string;
  ThemeMode: FrameScopeThemeMode;
  CloseWindowBehavior: FrameScopeCloseWindowBehavior;
  TrayEnabled: boolean;
  CpuTelemetry: FrameScopeCpuTelemetryConfig;
  Targets: FrameScopeTargetConfig[];
}

export interface StateSnapshotPayload {
  bridgeStatus: string;
  bridgeVersion: number;
  generatedAt: string;
  root: string;
  watcher: {
    running: boolean;
    pid: number;
    processName: string;
    processRole: string;
    workerExplanation: string;
    statePath: string;
    completedRuns: number;
    lastReport: string;
    lastError: string;
  };
  config: {
    exists: boolean;
    path: string;
    enabledTargetCount: number;
    targetCount: number;
    dataRoot: string;
  };
  host: {
    windowVisible: boolean;
    trayAvailable: boolean;
    closeWindowBehavior: FrameScopeCloseWindowBehavior;
  };
  reports: {
    historyPath: string;
    historyExists: boolean;
  };
}

export interface ConfigPayload {
  status: "loaded" | "saved" | string;
  configPath: string;
  config: FrameScopeConfig;
  enabledTargetCount: number;
  targetCount: number;
  resolvedDataRoot: string;
  loadedAt: string;
}

export interface ConfigSaveRequestPayload {
  config: FrameScopeConfig;
}

export interface ProcessesRefreshRequestPayload {
  query?: string;
}

export interface ProcessesRefreshAcceptedPayload {
  status: "accepted" | "in_flight" | string;
  requestId: string;
  message: string;
}

export interface ProcessInfo {
  processName: string;
  processId: number;
  windowTitle: string;
  displayText: string;
}

export interface ProcessesRefreshedEventPayload {
  requestId: string;
  status: "completed" | string;
  query: string;
  count: number;
  truncated: boolean;
  processes: ProcessInfo[];
  refreshedAt: string;
}

export interface MonitorActionAcceptedPayload {
  status: "accepted" | "in_flight" | string;
  requestId: string;
  action: "monitor.start" | "monitor.stop" | string;
  message: string;
}

export interface ReportListPayload {
  status: "loaded" | string;
  historyPath: string;
  dataRoot: string;
  count: number;
  reports: ReportListItem[];
  loadedAt: string;
}

export interface ReportListItem {
  reportId: string;
  game: string;
  processName: string;
  time: string;
  runDir: string;
  reportHtml: string;
  monitorExitCode: number;
  reportExists: boolean;
  runDirExists: boolean;
  canOpenReport: boolean;
  canOpenDirectory: boolean;
  canRegenerate: boolean;
  reportSizeBytes: number;
  lastWriteTime: string;
  reportKind: string;
  frameCount: number;
  hasFrameData: boolean;
  processSamplerStatus?: string;
  processSamplerValidRows?: number;
  systemSamplerStatus?: string;
  systemSamplerValidRows?: number;
}

export interface ReportActionRequestPayload {
  reportId: string;
}

export interface ReportActionPayload extends ReportListItem {
  status: string;
  message: string;
  [key: string]: unknown;
}

export interface DiagnosticsGenerateRequestPayload {
  reportId?: string;
}

export interface LongActionAcceptedPayload {
  status: "accepted" | "in_flight" | string;
  requestId: string;
  action: string;
  message: string;
}

export interface LogsOpenDirectoryPayload {
  status: "directory_opened" | string;
  message: string;
  directory: string;
  logFile?: string;
  [key: string]: unknown;
}

export interface ReportProgressEventPayload {
  requestId?: string;
  status: "completed" | "error" | string;
  action?: string;
  ok?: boolean;
  code?: string;
  message?: string;
  percent?: number;
  reportId?: string;
  runDir?: string;
  reportHtml?: string;
  markdownPath?: string;
  jsonPath?: string;
  [key: string]: unknown;
}

export interface TargetsPayload {
  status: "loaded" | "saved" | string;
  configPath: string;
  dataRoot: string;
  resolvedDataRoot: string;
  openReportOnComplete: boolean;
  enabledTargetCount: number;
  targetCount: number;
  targets: FrameScopeTargetConfig[];
  loadedAt: string;
}

export interface TargetsSaveRequestPayload {
  targets: FrameScopeTargetConfig[];
  dataRoot?: string;
  openReportOnComplete?: boolean;
}

export interface StatusEventPayload {
  requestId?: string;
  status?: string;
  message?: string;
  [key: string]: unknown;
}

export interface HostWindowChangedEventPayload {
  visible: boolean;
  inTray: boolean;
  closeWindowBehavior: FrameScopeCloseWindowBehavior;
  reason?: string;
}

export interface ErrorEventPayload extends BridgeError {
  requestId?: string;
  type?: string;
}

export interface BridgeRequestOptions {
  timeoutMs?: number;
}

export interface FrameScopeBridgeAdapter {
  readonly environment: BridgeEnvironment;
  request<TPayload>(
    type: BridgeRequestType,
    payload?: Record<string, unknown>,
    options?: BridgeRequestOptions,
  ): Promise<TPayload>;
  subscribe<TPayload>(
    type: BridgeEventType,
    listener: (event: BridgeEventEnvelope<TPayload>) => void,
  ): () => void;
}
