using System;
using System.Collections;
using System.Collections.Generic;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using System.Web.Script.Serialization;

public static partial class FrameScopeDiagnostics
{
    private static Dictionary<string, object> BuildSoftwareSection()
    {
        Assembly assembly = typeof(FrameScopeDiagnostics).Assembly;
        string assemblyVersion = Convert.ToString(assembly.GetName().Version, CultureInfo.InvariantCulture);
        string version = string.IsNullOrWhiteSpace(assemblyVersion) || assemblyVersion == "0.0.0.0" ? ProductVersion : assemblyVersion;
        return new Dictionary<string, object>
        {
            { "name", "FrameScope Monitor" },
            { "version", version },
            { "process", RedactForPrivacy(Process.GetCurrentProcess().ProcessName) },
            { "is64BitProcess", Environment.Is64BitProcess }
        };
    }

    private static Dictionary<string, object> BuildSystemSection()
    {
        return new Dictionary<string, object>
        {
            { "osVersion", RedactForPrivacy(Environment.OSVersion.ToString()) },
            { "is64BitOperatingSystem", Environment.Is64BitOperatingSystem },
            { "processorCount", Environment.ProcessorCount },
            { "machineName", "[redacted]" },
            { "user", "[redacted]" }
        };
    }

    private static Dictionary<string, object> BuildSettingsSection(FrameScopeConfig config)
    {
        List<Dictionary<string, object>> targets = new List<Dictionary<string, object>>();
        foreach (FrameScopeTarget target in config.Targets ?? new List<FrameScopeTarget>())
        {
            if (target == null) continue;
            targets.Add(new Dictionary<string, object>
            {
                { "enabled", target.Enabled },
                { "name", RedactForPrivacy(target.Name ?? "") },
                { "processName", RedactForPrivacy(target.ProcessName ?? "") },
                { "sampleIntervalMs", target.SampleIntervalMs },
                { "processSampleIntervalMs", target.ProcessSampleIntervalMs },
                { "slowSampleIntervalMs", target.SlowSampleIntervalMs },
                { "openReportOnComplete", target.OpenReportOnComplete }
            });
        }

        return new Dictionary<string, object>
        {
            { "pollIntervalMs", config.PollIntervalMs },
            { "dataRoot", RedactForPrivacy(config.DataRoot ?? "") },
            { "openReportOnComplete", config.OpenReportOnComplete },
            { "monitorScript", config.MonitorScript ?? "" },
            { "enableVerboseLogs", config.EnableVerboseLogs },
            { "enablePerformanceDiagnosticsLogs", config.EnablePerformanceDiagnosticsLogs },
            { "autoGenerateDiagnosticReport", config.AutoGenerateDiagnosticReport },
            { "logRetentionDays", config.LogRetentionDays },
            { "maxLogDiskMb", config.MaxLogDiskMb },
            { "targets", targets }
        };
    }

    private static List<Dictionary<string, object>> BuildTargetDetectionSection(FrameScopeConfig config)
    {
        List<Dictionary<string, object>> rows = new List<Dictionary<string, object>>();
        foreach (FrameScopeTarget target in config.Targets ?? new List<FrameScopeTarget>())
        {
            if (target == null || string.IsNullOrWhiteSpace(target.ProcessName)) continue;
            List<string> aliases = FrameScopeCapturePlanner.BuildTargetProcessBaseNames(target.ProcessName, target.Name);
            List<Dictionary<string, object>> processes = new List<Dictionary<string, object>>();
            foreach (string alias in aliases)
            {
                foreach (Process process in SafeGetProcesses(alias))
                {
                    try
                    {
                        processes.Add(new Dictionary<string, object>
                        {
                            { "pid", process.Id },
                            { "processName", process.ProcessName + ".exe" },
                            { "hasMainWindow", process.MainWindowHandle != IntPtr.Zero },
                            { "windowTitle", RedactForPrivacy(process.MainWindowTitle ?? "") }
                        });
                    }
                    catch { }
                    finally { try { process.Dispose(); } catch { } }
                }
            }
            rows.Add(new Dictionary<string, object>
            {
                { "enabled", target.Enabled },
                { "target", target.Name },
                { "processName", target.ProcessName },
                { "aliases", aliases },
                { "runningCount", processes.Count },
                { "processes", processes }
            });
        }
        return rows;
    }

    private static Dictionary<string, object> BuildRecentSessionSection(string runDir, Dictionary<string, object> status, Dictionary<string, object> summary, Dictionary<string, object> manifest)
    {
        return new Dictionary<string, object>
        {
            { "runDir", RedactForPrivacy(runDir ?? "") },
            { "statusPhase", GetString(status, "Phase") },
            { "targetProcess", FirstNonEmpty(GetString(summary, "TargetProcess"), GetString(status, "TargetProcess")) },
            { "reportHtml", RedactForPrivacy(FirstNonEmpty(GetString(summary, "ReportHtml"), GetString(status, "LastReport"))) },
            { "hasFrameData", GetObject(manifest, "hasFrameData") },
            { "reportKind", FirstNonEmpty(GetString(manifest, "reportKind"), GetString(status, "ReportKind")) },
            { "frames", FirstNonNull(GetObject(manifest, "frames"), GetObject(status, "FrameCount")) }
        };
    }

    private static Dictionary<string, object> BuildFpsSummary(Dictionary<string, object> status, Dictionary<string, object> manifest)
    {
        Dictionary<string, object> frameStats = GetMap(manifest, "frameStats");
        return new Dictionary<string, object>
        {
            { "hasFrameData", GetObject(manifest, "hasFrameData") },
            { "frames", FirstNonNull(GetObject(manifest, "frames"), GetObject(status, "FrameCount")) },
            { "presentMonCsvRows", GetObject(status, "PresentMonCsvRows") },
            { "averageFps", GetObject(frameStats, "average") },
            { "low1", GetObject(frameStats, "low1") },
            { "low01", GetObject(frameStats, "low01") },
            { "minInstant", GetObject(frameStats, "minInstant") }
        };
    }

    private static Dictionary<string, object> BuildReportGenerationSection(Dictionary<string, object> status, Dictionary<string, object> progress)
    {
        return new Dictionary<string, object>
        {
            { "reportProgressPhase", FirstNonEmpty(GetString(status, "ReportProgressPhase"), GetString(progress, "ReportProgressPhase")) },
            { "reportProgressPercent", FirstNonNull(GetObject(status, "ReportProgressPercent"), GetObject(progress, "ReportProgressPercent")) },
            { "reportProgressError", FirstNonEmpty(GetString(status, "ReportProgressError"), GetString(progress, "ReportProgressError")) },
            { "reportCanRetry", FirstNonNull(GetObject(status, "ReportCanRetry"), GetObject(progress, "ReportCanRetry")) },
            { "reportError", GetString(status, "ReportError") }
        };
    }

    private static Dictionary<string, object> BuildPerformanceSection(string runDir)
    {
        Dictionary<string, object> section = new Dictionary<string, object>();
        try
        {
            Process current = Process.GetCurrentProcess();
            section["currentProcessPrivateMb"] = Math.Round(current.PrivateMemorySize64 / 1024.0 / 1024.0, 1);
            section["currentProcessWorkingSetMb"] = Math.Round(current.WorkingSet64 / 1024.0 / 1024.0, 1);
            current.Dispose();
        }
        catch { }
        section["processSamplesBytes"] = FileSize(Path.Combine(runDir ?? "", "process-samples.csv"));
        section["systemSamplesBytes"] = FileSize(Path.Combine(runDir ?? "", "system-samples.csv"));
        section["presentMonCsvBytes"] = FileSize(Path.Combine(runDir ?? "", "presentmon.csv"));
        return section;
    }

    private static Dictionary<string, object> BuildErrorsSection(string appRoot, string runDir)
    {
        List<string> errors = new List<string>();
        AddFilteredTail(errors, Path.Combine(appRoot ?? "", "framescope-watcher.log"));
        AddFilteredTail(errors, Path.Combine(runDir ?? "", "report-generation.log"));
        AddFilteredTail(errors, Path.Combine(runDir ?? "", "error.txt"));
        return new Dictionary<string, object>
        {
            { "recentErrors", errors.Take(80).ToList() }
        };
    }

    private static Dictionary<string, object> BuildCaptureChainSection(Dictionary<string, object> status, Dictionary<string, object> summary, Dictionary<string, object> manifest)
    {
        return new Dictionary<string, object>
        {
            { "frameCaptureStatus", FirstNonEmpty(GetString(status, "FrameCaptureStatus"), GetString(summary, "FrameCaptureStatus"), GetString(manifest, "frameCaptureStatus")) },
            { "frameCaptureMessage", FirstNonEmpty(GetString(status, "FrameCaptureMessage"), GetString(summary, "FrameCaptureMessage"), GetString(manifest, "frameCaptureMessage")) },
            { "presentMonCaptureMode", FirstNonEmpty(GetString(status, "PresentMonCaptureMode"), GetString(summary, "PresentMonCaptureMode"), GetString(manifest, "presentMonCaptureMode")) },
            { "presentMonCaptureTarget", FirstNonEmpty(GetString(status, "PresentMonCaptureTarget"), GetString(summary, "PresentMonCaptureTarget")) },
            { "presentMonExitCode", FirstNonNull(GetObject(status, "PresentMonExitCode"), GetObject(summary, "PresentMonExitCode")) },
            { "presentMonCsvExists", FirstNonNull(GetObject(status, "PresentMonCsvExists"), GetObject(summary, "PresentMonCsvExists")) },
            { "presentMonCsvRows", FirstNonNull(GetObject(status, "PresentMonCsvRows"), GetObject(summary, "PresentMonCsvRows")) }
        };
    }
}
