using System;
using System.Collections.Generic;
using System.IO;

public static class FrameScopeConfigStoreTests
{
    public static int Main()
    {
        CreateDefaultConfigUsesNativeModeAndSeparateDataRoot();
        NormalizeKeepsSlowSamplerAtLeastAsSlowAsFrameSampler();
        BuildConfigFromEditableTargetsPreservesHiddenIntervals();
        SaveAndLoadRoundTripsNormalizedConfig();
        Console.WriteLine("FrameScopeConfigStoreTests: PASS");
        return 0;
    }

    private static void CreateDefaultConfigUsesNativeModeAndSeparateDataRoot()
    {
        FrameScopeConfig config = FrameScopeConfigStore.CreateDefaultConfig();
        AssertEqual("native-csharp", config.MonitorScript, "default monitor mode");
        AssertTrue(config.DataRoot.EndsWith(Path.Combine("FrameScopeMonitorData", "framescope-runs"), StringComparison.OrdinalIgnoreCase), "default data root should not be under app directory");
        AssertEqual(9, config.Targets.Count, "default target count");
        AssertEqual(14, config.LogRetentionDays, "default log retention");
        AssertEqual(100, config.MaxLogDiskMb, "default log disk cap");
    }

    private static void NormalizeKeepsSlowSamplerAtLeastAsSlowAsFrameSampler()
    {
        FrameScopeConfig config = new FrameScopeConfig
        {
            PollIntervalMs = 0,
            DataRoot = "",
            MonitorScript = "Monitor-CS2-HighFreq.ps1",
            LogRetentionDays = -9,
            MaxLogDiskMb = 0,
            Targets = new List<FrameScopeTarget>
            {
                new FrameScopeTarget
                {
                    Enabled = true,
                    Name = "High interval",
                    ProcessName = "High.exe",
                    SampleIntervalMs = 1500,
                    ProcessSampleIntervalMs = 10,
                    SlowSampleIntervalMs = 200
                }
            }
        };

        FrameScopeConfigStore.Normalize(config);

        AssertEqual(1000, config.PollIntervalMs, "poll interval fallback");
        AssertEqual("native-csharp", config.MonitorScript, "legacy monitor mode normalization");
        AssertEqual(14, config.LogRetentionDays, "log retention fallback");
        AssertEqual(100, config.MaxLogDiskMb, "log disk cap fallback");
        AssertEqual(100, config.Targets[0].ProcessSampleIntervalMs, "process sampler lower bound");
        AssertEqual(1500, config.Targets[0].SlowSampleIntervalMs, "slow sampler must not become faster than frame sampler");
    }

    private static void BuildConfigFromEditableTargetsPreservesHiddenIntervals()
    {
        FrameScopeConfig existing = new FrameScopeConfig
        {
            PollIntervalMs = 2222,
            DataRoot = @"C:\OldDataRoot",
            OpenReportOnComplete = true,
            EnableVerboseLogs = true,
            EnablePerformanceDiagnosticsLogs = true,
            AutoGenerateDiagnosticReport = true,
            LogRetentionDays = 30,
            MaxLogDiskMb = 250,
            MonitorScript = "native-csharp",
            Targets = new List<FrameScopeTarget>
            {
                new FrameScopeTarget
                {
                    Enabled = true,
                    Name = "Example Game",
                    ProcessName = "Example.exe",
                    SampleIntervalMs = 120,
                    ProcessSampleIntervalMs = 250,
                    SlowSampleIntervalMs = 3000,
                    OpenReportOnComplete = true
                }
            }
        };

        FrameScopeConfig merged = FrameScopeConfigStore.BuildConfigFromEditableTargets(
            existing,
            @"C:\NewDataRoot",
            false,
            new[]
            {
                new FrameScopeTarget
                {
                    Enabled = true,
                    Name = "Example Game",
                    ProcessName = "Example.exe",
                    SampleIntervalMs = 120,
                    OpenReportOnComplete = false
                }
            });

        AssertEqual(2222, merged.PollIntervalMs, "poll interval should be preserved");
        AssertEqual(@"C:\NewDataRoot", merged.DataRoot, "editable data root should be used");
        AssertEqual(false, merged.OpenReportOnComplete, "editable global auto-open should be used");
        AssertEqual(true, merged.EnableVerboseLogs, "verbose setting should be preserved");
        AssertEqual(true, merged.EnablePerformanceDiagnosticsLogs, "perf setting should be preserved");
        AssertEqual(true, merged.AutoGenerateDiagnosticReport, "auto diagnostic setting should be preserved");
        AssertEqual(30, merged.LogRetentionDays, "retention setting should be preserved");
        AssertEqual(250, merged.MaxLogDiskMb, "disk cap setting should be preserved");
        AssertEqual(250, merged.Targets[0].ProcessSampleIntervalMs, "hidden process interval should be preserved");
        AssertEqual(3000, merged.Targets[0].SlowSampleIntervalMs, "hidden slow interval should be preserved");
        AssertEqual(false, merged.Targets[0].OpenReportOnComplete, "editable target auto-open should be used");
    }

    private static void SaveAndLoadRoundTripsNormalizedConfig()
    {
        string dir = Path.Combine(Path.GetTempPath(), "framescope-config-store-tests-" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(dir);
        string path = Path.Combine(dir, "framescope-config.json");
        try
        {
            FrameScopeConfig config = new FrameScopeConfig
            {
                PollIntervalMs = 333,
                DataRoot = Path.Combine(dir, "runs"),
                OpenReportOnComplete = true,
                MonitorScript = "native-csharp",
                Targets = new List<FrameScopeTarget>
                {
                    new FrameScopeTarget { Enabled = true, Name = "Roundtrip", ProcessName = "Roundtrip.exe", SampleIntervalMs = 60, ProcessSampleIntervalMs = 80, SlowSampleIntervalMs = 40, OpenReportOnComplete = true }
                }
            };

            FrameScopeConfigStore.Save(path, config);
            FrameScopeConfig loaded = FrameScopeConfigStore.Load(path);

            AssertEqual(333, loaded.PollIntervalMs, "saved poll interval");
            AssertEqual(100, loaded.Targets[0].ProcessSampleIntervalMs, "saved process interval normalization");
            AssertEqual(1000, loaded.Targets[0].SlowSampleIntervalMs, "saved slow interval normalization");
        }
        finally
        {
            try { Directory.Delete(dir, true); }
            catch { }
        }
    }

    private static void AssertEqual<T>(T expected, T actual, string label)
    {
        if (!EqualityComparer<T>.Default.Equals(expected, actual))
        {
            throw new Exception(label + ": expected <" + expected + "> but got <" + actual + ">");
        }
    }

    private static void AssertTrue(bool condition, string label)
    {
        if (!condition) throw new Exception(label);
    }
}
