using System;
using System.Collections.Generic;

public static class FrameScopeLoggingPolicyTests
{
    public static int Main()
    {
        DefaultConfigDoesNotEnableVerboseOrPerformanceNoise();
        AutomaticDiagnosticsSkipHealthyFullReports();
        AutomaticDiagnosticsRunForDiagnosticOrFailedReports();
        RateLimiterSuppressesRepeatsButKeepsStateChangesAndHeartbeats();
        Console.WriteLine("FrameScopeLoggingPolicyTests: PASS");
        return 0;
    }

    private static void DefaultConfigDoesNotEnableVerboseOrPerformanceNoise()
    {
        FrameScopeConfig config = FrameScopeConfigStore.CreateDefaultConfig();

        AssertEqual(false, FrameScopeLoggingPolicy.IsVerboseEnabled(config), "verbose default");
        AssertEqual(false, FrameScopeLoggingPolicy.IsPerformanceDiagnosticsEnabled(config), "performance default");
    }

    private static void AutomaticDiagnosticsSkipHealthyFullReports()
    {
        Dictionary<string, object> status = new Dictionary<string, object>(StringComparer.OrdinalIgnoreCase)
        {
            { "Phase", "done" },
            { "ReportKind", "full" },
            { "ReportFrameCount", 240 },
            { "ReportError", "" },
            { "FrameCaptureStatus", "captured" }
        };

        AssertEqual(false, FrameScopeLoggingPolicy.ShouldAutoGenerateDiagnosticReport(status, 0), "healthy full report");
    }

    private static void AutomaticDiagnosticsRunForDiagnosticOrFailedReports()
    {
        Dictionary<string, object> diagnosticStatus = new Dictionary<string, object>(StringComparer.OrdinalIgnoreCase)
        {
            { "Phase", "done" },
            { "ReportKind", "diagnostic" },
            { "ReportFrameCount", 0 },
            { "ReportError", "No frame data was captured." },
            { "FrameCaptureStatus", "no-frame-data" }
        };
        Dictionary<string, object> failedStatus = new Dictionary<string, object>(StringComparer.OrdinalIgnoreCase)
        {
            { "Phase", "error" },
            { "ReportKind", "unknown" },
            { "ReportError", "Report generation failed." },
            { "FrameCaptureStatus", "presentmon-etw-access-denied" }
        };

        AssertEqual(true, FrameScopeLoggingPolicy.ShouldAutoGenerateDiagnosticReport(diagnosticStatus, 0), "diagnostic report");
        AssertEqual(true, FrameScopeLoggingPolicy.ShouldAutoGenerateDiagnosticReport(failedStatus, 1), "failed monitor");
    }

    private static void RateLimiterSuppressesRepeatsButKeepsStateChangesAndHeartbeats()
    {
        FrameScopeLogRateLimiter limiter = new FrameScopeLogRateLimiter();
        DateTime start = new DateTime(2026, 6, 1, 10, 0, 0, DateTimeKind.Utc);
        TimeSpan interval = TimeSpan.FromSeconds(15);

        AssertEqual(true, limiter.ShouldWrite("target-scan:missing", "detected=none", start, interval), "first state should write");
        AssertEqual(false, limiter.ShouldWrite("target-scan:missing", "detected=none", start.AddSeconds(1), interval), "same state inside interval should be suppressed");
        AssertEqual(true, limiter.ShouldWrite("target-scan:missing", "detected=TslGame:42", start.AddSeconds(2), interval), "changed state should write");
        AssertEqual(false, limiter.ShouldWrite("target-scan:missing", "detected=TslGame:42", start.AddSeconds(3), interval), "changed state repeat should be suppressed");
        AssertEqual(true, limiter.ShouldWrite("target-scan:missing", "detected=TslGame:42", start.AddSeconds(18), interval), "same state after interval should write");
    }

    private static void AssertEqual<T>(T expected, T actual, string label)
    {
        if (!EqualityComparer<T>.Default.Equals(expected, actual))
        {
            throw new Exception(label + ": expected <" + expected + "> but got <" + actual + ">");
        }
    }
}
