using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Web.Script.Serialization;

public static class FrameScopeDiagnosticsTests
{
    private static readonly JavaScriptSerializer Json = new JavaScriptSerializer { MaxJsonLength = int.MaxValue };

    public static int Main()
    {
        try
        {
            ConfigNormalizesDiagnosticSettings();
            RedactsUserAndSecrets();
            GeneratesDiagnosticReportWithRequiredSections();
            LegacyRunSchemaRemainsReadable();
            GeneratesDiagnosticReportWithPresentMonEtwAccessDeniedFields();
            LatestRunDiscoverySkipsNoisyDataRootDirectories();
            CleanupDeletesOldArtifactsAndEnforcesSizeLimit();
            Console.WriteLine("FrameScopeDiagnosticsTests: PASS");
            return 0;
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine(ex.GetType().FullName + ": " + ex.Message);
            return 1;
        }
    }

    private static void ConfigNormalizesDiagnosticSettings()
    {
        FrameScopeConfig config = new FrameScopeConfig
        {
            PollIntervalMs = 1000,
            DataRoot = "runs",
            LogRetentionDays = -1,
            MaxLogDiskMb = 0
        };

        FrameScopeConfigStore.Normalize(config);

        AssertEqual(false, config.EnableVerboseLogs, "verbose default");
        AssertEqual(false, config.EnablePerformanceDiagnosticsLogs, "perf diagnostics default");
        AssertEqual(false, config.AutoGenerateDiagnosticReport, "auto diagnostic default");
        AssertEqual(14, config.LogRetentionDays, "retention default");
        AssertEqual(100, config.MaxLogDiskMb, "disk cap default");
    }

    private static void RedactsUserAndSecrets()
    {
        string userProfile = Environment.GetFolderPath(Environment.SpecialFolder.UserProfile);
        string sample = userProfile + "\\FrameScopeMonitor token=abc123 password=secret";
        string redacted = FrameScopeDiagnostics.RedactForPrivacy(sample);

        AssertTrue(!redacted.Contains(userProfile), "full user profile should be redacted");
        AssertTrue(!redacted.Contains(Environment.UserName), "username should be redacted");
        AssertTrue(!redacted.Contains("abc123"), "token value should be redacted");
        AssertTrue(!redacted.Contains("secret"), "password value should be redacted");
    }

    private static void GeneratesDiagnosticReportWithRequiredSections()
    {
        string dir = Path.Combine(Path.GetTempPath(), "framescope-diagnostics-tests-" + Guid.NewGuid().ToString("N"));
        string appRoot = Path.Combine(dir, "app");
        string dataRoot = Path.Combine(dir, "data");
        string runDir = Path.Combine(dataRoot, "PUBG", "PUBG-20260510-010203");
        Directory.CreateDirectory(appRoot);
        Directory.CreateDirectory(runDir);

        try
        {
            File.WriteAllText(Path.Combine(appRoot, "framescope-watcher.log"),
                "2026-05-10T01:02:03Z report-generate-failed path=" + Environment.GetFolderPath(Environment.SpecialFolder.UserProfile) + Environment.NewLine,
                Encoding.UTF8);
            string charts = Path.Combine(runDir, "charts");
            string reportHtml = Path.Combine(charts, "framescope-interactive-report.html");
            File.WriteAllText(Path.Combine(runDir, "status.json"), Json.Serialize(new Dictionary<string, object>
            {
                { "Phase", "done" },
                { "TargetProcess", "TslGame.exe" },
                { "FrameCaptureStatus", "captured" },
                { "PresentMonCsvRows", 240 },
                { "ReportHtml", reportHtml },
                { "ReportFrameCount", 240 },
                { "ReportHasFrameData", true },
                { "ReportKind", "partial" },
                { "ProcessSamplerStatus", "healthy" },
                { "ProcessSamplerValidRows", 10 },
                { "SystemSamplerStatus", "failed" },
                { "SystemSamplerValidRows", 0 },
                { "ReportGenerationStartedAt", "2026-07-11T01:02:03.0000000Z" },
                { "ReportGenerationEndedAt", "2026-07-11T01:02:05.0000000Z" },
                { "ReportGenerationTimedOut", true },
                { "ReportGenerationExitCode", -1 },
                { "ReportCanRetry", true }
            }), Encoding.UTF8);
            File.WriteAllText(Path.Combine(runDir, "summary.json"),
                "{\"TargetProcess\":\"legacy-wrong.exe\",\"FrameCaptureStatus\":\"captured\",\"ReportHtml\":\"legacy-wrong.html\"}",
                Encoding.UTF8);
            Directory.CreateDirectory(charts);
            File.WriteAllText(Path.Combine(charts, "framescope-interactive-manifest.json"),
                "{\"hasFrameData\":false,\"frames\":1,\"reportKind\":\"full\",\"frameCaptureStatus\":\"captured\"}",
                Encoding.UTF8);
            File.WriteAllText(Path.Combine(charts, "framescope-interactive-data.js"),
                "window.FRAMESCOPE_DATA = {\"frameStats\":{\"average\":144.5,\"low1\":90.0,\"low01\":61.0,\"minInstant\":42.0}};",
                Encoding.UTF8);
            File.WriteAllText(Path.Combine(runDir, "monitor-error.txt"), "current monitor failed", Encoding.UTF8);

            FrameScopeConfig config = new FrameScopeConfig
            {
                DataRoot = dataRoot,
                Targets = new List<FrameScopeTarget>
                {
                    new FrameScopeTarget { Enabled = true, Name = "PUBG: BATTLEGROUNDS", ProcessName = "TslGame.exe" }
                }
            };
            FrameScopeConfigStore.Normalize(config);

            FrameScopeDiagnosticReportResult result = FrameScopeDiagnostics.GenerateReport(config, appRoot, dataRoot, "unit-test", runDir);
            string markdown = File.ReadAllText(result.MarkdownPath, Encoding.UTF8);
            string json = File.ReadAllText(result.JsonPath, Encoding.UTF8);
            Dictionary<string, object> report = Json.Deserialize<Dictionary<string, object>>(json);
            Dictionary<string, object> recent = GetMap(report, "recentSession");
            Dictionary<string, object> fps = GetMap(report, "fpsSummary");
            Dictionary<string, object> generation = GetMap(report, "reportGeneration");

            AssertTrue(File.Exists(result.MarkdownPath), "markdown report exists");
            AssertTrue(File.Exists(result.JsonPath), "json report exists");
            AssertTrue(markdown.Contains("Software"), "software section");
            AssertTrue(markdown.Contains("Settings"), "settings section");
            AssertTrue(markdown.Contains("Target Detection"), "target detection section");
            AssertTrue(markdown.Contains("Capture Chain"), "capture chain section");
            AssertTrue(json.Contains("\"fpsSummary\""), "json fps summary");
            AssertEqual("TslGame.exe", Convert.ToString(recent["targetProcess"]), "current target process");
            AssertEqual(240, Convert.ToInt32(recent["frames"]), "current frame count");
            AssertEqual("partial", Convert.ToString(recent["reportKind"]), "current report kind");
            AssertEqual(144.5, Convert.ToDouble(fps["averageFps"]), "data.js average FPS");
            AssertEqual(42.0, Convert.ToDouble(fps["minInstant"]), "data.js min FPS");
            AssertEqual(true, Convert.ToBoolean(generation["reportGenerationTimedOut"]), "report timeout diagnostics");
            AssertEqual("healthy", Convert.ToString(generation["processSamplerStatus"]), "process sampler diagnostics");
            AssertEqual("failed", Convert.ToString(generation["systemSamplerStatus"]), "system sampler diagnostics");
            AssertTrue(json.Contains("current monitor failed"), "current monitor error file");
            AssertTrue(!markdown.Contains(Environment.UserName), "markdown redacts username");
        }
        finally
        {
            try { Directory.Delete(dir, true); }
            catch { }
        }
    }

    private static void LegacyRunSchemaRemainsReadable()
    {
        string dir = Path.Combine(Path.GetTempPath(), "framescope-diagnostics-legacy-tests-" + Guid.NewGuid().ToString("N"));
        string appRoot = Path.Combine(dir, "app");
        string dataRoot = Path.Combine(dir, "data");
        string runDir = Path.Combine(dataRoot, "Legacy", "Legacy-20250101-010203");
        Directory.CreateDirectory(appRoot);
        Directory.CreateDirectory(Path.Combine(runDir, "charts"));
        try
        {
            File.WriteAllText(Path.Combine(runDir, "status.json"),
                "{\"Phase\":\"done\",\"TargetProcess\":\"Legacy.exe\",\"LastReport\":\"legacy-report.html\",\"FrameCount\":12,\"ReportKind\":\"diagnostic\"}", Encoding.UTF8);
            File.WriteAllText(Path.Combine(runDir, "error.txt"), "legacy report failed", Encoding.UTF8);
            File.WriteAllText(Path.Combine(runDir, "charts", "framescope-interactive-manifest.json"),
                "{\"hasFrameData\":false,\"frames\":12,\"reportKind\":\"diagnostic\"}", Encoding.UTF8);
            FrameScopeConfig config = FrameScopeConfigStore.CreateDefaultConfig();
            config.DataRoot = dataRoot;

            Dictionary<string, object> report = FrameScopeDiagnostics.BuildReport(config, appRoot, dataRoot, "legacy-test", runDir);
            Dictionary<string, object> recent = GetMap(report, "recentSession");
            AssertEqual(12, Convert.ToInt32(recent["frames"]), "legacy frame count");
            AssertEqual("diagnostic", Convert.ToString(recent["reportKind"]), "legacy report kind");
            AssertTrue(Convert.ToString(recent["reportHtml"]).Contains("legacy-report.html"), "legacy report path");
            AssertTrue(Json.Serialize(report).Contains("legacy report failed"), "legacy error fallback");
        }
        finally { try { Directory.Delete(dir, true); } catch { } }
    }

    private static void GeneratesDiagnosticReportWithPresentMonEtwAccessDeniedFields()
    {
        string dir = Path.Combine(Path.GetTempPath(), "framescope-diagnostics-access-denied-tests-" + Guid.NewGuid().ToString("N"));
        string appRoot = Path.Combine(dir, "app");
        string dataRoot = Path.Combine(dir, "data");
        string runDir = Path.Combine(dataRoot, "Battlefield-6", "Battlefield-6-20260524-024833");
        Directory.CreateDirectory(appRoot);
        Directory.CreateDirectory(runDir);
        Directory.CreateDirectory(Path.Combine(runDir, "charts"));

        try
        {
            string message = "PresentMon 无法启动 ETW trace，需要管理员/Performance Log Users/系统 ETW 权限检查。";
            File.WriteAllText(Path.Combine(runDir, "status.json"),
                "{\"Phase\":\"done\",\"FrameCaptureStatus\":\"presentmon-etw-access-denied\",\"FrameCaptureMessage\":\"" + message + "\",\"PresentMonFailureCategory\":\"presentmon-etw-access-denied\",\"PresentMonEtwAccessDenied\":true,\"PresentMonExitCode\":6,\"PresentMonCsvExists\":false,\"PresentMonCsvRows\":0,\"PresentMonPreflightIsElevated\":true,\"PresentMonPreflightInPerformanceLogUsers\":false,\"PresentMonPreflightToolExists\":true}",
                Encoding.UTF8);
            File.WriteAllText(Path.Combine(runDir, "summary.json"),
                "{\"TargetProcess\":\"bf6.exe\",\"FrameCaptureStatus\":\"presentmon-etw-access-denied\",\"FrameCaptureMessage\":\"" + message + "\",\"PresentMonFailureCategory\":\"presentmon-etw-access-denied\",\"PresentMonEtwAccessDenied\":true,\"PresentMonExitCode\":6,\"PresentMonPreflightIsElevated\":true,\"PresentMonPreflightInPerformanceLogUsers\":false,\"PresentMonPreflightToolExists\":true}",
                Encoding.UTF8);
            File.WriteAllText(Path.Combine(runDir, "charts", "framescope-interactive-manifest.json"),
                "{\"hasFrameData\":false,\"frames\":0,\"reportKind\":\"diagnostic\",\"frameCaptureStatus\":\"presentmon-etw-access-denied\",\"frameCaptureMessage\":\"" + message + "\",\"presentMonFailureCategory\":\"presentmon-etw-access-denied\",\"presentMonEtwAccessDenied\":true,\"presentMonPreflightIsElevated\":true,\"presentMonPreflightInPerformanceLogUsers\":false,\"presentMonPreflightToolExists\":true}",
                Encoding.UTF8);

            FrameScopeConfig config = new FrameScopeConfig
            {
                DataRoot = dataRoot,
                Targets = new List<FrameScopeTarget>
                {
                    new FrameScopeTarget { Enabled = true, Name = "Battlefield 6", ProcessName = "bf6.exe" }
                }
            };
            FrameScopeConfigStore.Normalize(config);

            FrameScopeDiagnosticReportResult result = FrameScopeDiagnostics.GenerateReport(config, appRoot, dataRoot, "unit-test-access-denied", runDir);
            string markdown = File.ReadAllText(result.MarkdownPath, Encoding.UTF8);
            string json = File.ReadAllText(result.JsonPath, Encoding.UTF8);

            AssertTrue(markdown.Contains("presentmon-etw-access-denied"), "markdown access denied status");
            AssertTrue(markdown.Contains("Performance Log Users"), "markdown remediation message");
            AssertTrue(json.Contains("\"presentMonPreflightIsElevated\":true"), "json elevated preflight");
            AssertTrue(json.Contains("\"presentMonPreflightInPerformanceLogUsers\":false"), "json PLU preflight");
            AssertTrue(json.Contains("\"presentMonPreflightToolExists\":true"), "json tool preflight");
        }
        finally
        {
            try { Directory.Delete(dir, true); }
            catch { }
        }
    }

    private static void LatestRunDiscoverySkipsNoisyDataRootDirectories()
    {
        string dir = Path.Combine(Path.GetTempPath(), "framescope-diagnostics-noise-tests-" + Guid.NewGuid().ToString("N"));
        string appRoot = Path.Combine(dir, "app");
        string dataRoot = Path.Combine(dir, "data");
        string validRun = Path.Combine(dataRoot, "CleanGame", "CleanGame-20260602-120000");
        string noisyRun = Path.Combine(dataRoot, "node_modules", "package", "fake-run");
        Directory.CreateDirectory(appRoot);
        Directory.CreateDirectory(validRun);
        Directory.CreateDirectory(noisyRun);

        try
        {
            string validStatus = Path.Combine(validRun, "status.json");
            File.WriteAllText(validStatus,
                "{\"Phase\":\"done\",\"TargetProcess\":\"Clean.exe\",\"FrameCaptureStatus\":\"captured\",\"PresentMonCsvRows\":12}",
                Encoding.UTF8);
            File.SetLastWriteTime(validStatus, DateTime.Now.AddMinutes(-1));

            string noisyStatus = Path.Combine(noisyRun, "status.json");
            File.WriteAllText(noisyStatus,
                "{\"Phase\":\"done\",\"TargetProcess\":\"Noisy.exe\",\"FrameCaptureStatus\":\"captured\",\"PresentMonCsvRows\":999}",
                Encoding.UTF8);
            File.SetLastWriteTime(noisyStatus, DateTime.Now);

            FrameScopeConfig config = new FrameScopeConfig
            {
                DataRoot = dataRoot,
                Targets = new List<FrameScopeTarget>
                {
                    new FrameScopeTarget { Enabled = true, Name = "Clean Game", ProcessName = "Clean.exe" }
                }
            };
            FrameScopeConfigStore.Normalize(config);

            FrameScopeDiagnosticReportResult result = FrameScopeDiagnostics.GenerateReport(config, appRoot, dataRoot, "unit-test-noise", "");
            string json = File.ReadAllText(result.JsonPath, Encoding.UTF8);

            AssertTrue(json.Contains("Clean.exe"), "latest run should come from clean data root run");
            AssertTrue(!json.Contains("Noisy.exe"), "latest run should skip noisy dependency directory");
        }
        finally
        {
            try { Directory.Delete(dir, true); }
            catch { }
        }
    }

    private static void CleanupDeletesOldArtifactsAndEnforcesSizeLimit()
    {
        string dir = Path.Combine(Path.GetTempPath(), "framescope-diagnostics-cleanup-tests-" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(dir);
        try
        {
            string oldDir = Path.Combine(dir, "diagnostic-old");
            string newDir = Path.Combine(dir, "diagnostic-new");
            Directory.CreateDirectory(oldDir);
            Directory.CreateDirectory(newDir);
            string oldFile = Path.Combine(oldDir, "old.md");
            string keepFile = Path.Combine(newDir, "keep.md");
            string largeFile = Path.Combine(newDir, "large.bin");
            File.WriteAllText(oldFile, "old");
            File.WriteAllBytes(keepFile, new byte[400 * 1024]);
            File.WriteAllBytes(largeFile, new byte[900 * 1024]);
            File.SetLastWriteTimeUtc(oldFile, DateTime.UtcNow.AddDays(-30));
            File.SetLastWriteTimeUtc(keepFile, DateTime.UtcNow.AddMinutes(-2));
            File.SetLastWriteTimeUtc(largeFile, DateTime.UtcNow.AddMinutes(-1));

            FrameScopeDiagnosticCleanupResult result = FrameScopeDiagnostics.CleanupDiagnosticReports(dir, 7, 1);

            AssertTrue(!File.Exists(oldFile), "old file deleted");
            AssertTrue(result.FilesDeleted >= 2, "old and over-limit files deleted");
            AssertTrue(TotalBytes(dir) <= 1024 * 1024, "size limit enforced");
        }
        finally
        {
            try { Directory.Delete(dir, true); }
            catch { }
        }
    }

    private static long TotalBytes(string dir)
    {
        long total = 0;
        foreach (string file in Directory.GetFiles(dir, "*", SearchOption.AllDirectories))
        {
            total += new FileInfo(file).Length;
        }
        return total;
    }

    private static Dictionary<string, object> GetMap(Dictionary<string, object> map, string key)
    {
        return (Dictionary<string, object>)map[key];
    }

    private static void AssertEqual<T>(T expected, T actual, string label)
    {
        if (!EqualityComparer<T>.Default.Equals(expected, actual))
        {
            throw new Exception(label + ": expected <" + expected + "> but got <" + actual + ">");
        }
    }

    private static void AssertTrue(bool condition, string label)
    {
        if (!condition) throw new Exception(label);
    }
}
