using System;
using System.Collections;
using System.Collections.Generic;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using System.Web.Script.Serialization;

public static class FrameScopeTargetLifecycleIntegrationTests
{
    private static readonly JavaScriptSerializer Json = new JavaScriptSerializer { MaxJsonLength = int.MaxValue };
    private static string retainedFixture = "";

    public static int Main(string[] args)
    {
        string helperReady = FrameScopePubgSimulationCommon.GetArgValue(args, "--helper-ready", "");
        if (!string.IsNullOrWhiteSpace(helperReady))
        {
            return RunTargetHelper(helperReady, FrameScopePubgSimulationCommon.GetArgValue(args, "--helper-stop", ""));
        }

        bool createdNew;
        using (var mutex = new Mutex(true, "Local\\FrameScopeTargetLifecycleIntegrationTests", out createdNew))
        {
            if (!createdNew)
            {
                Console.Error.WriteLine("FrameScopeTargetLifecycleIntegrationTests is already running.");
                return 1;
            }

            try
            {
                RunAliasHandoffScenario();
                RunOverlappingWatcherClaimScenario();
                Console.WriteLine("FrameScopeTargetLifecycleIntegrationTests: PASS");
                return 0;
            }
            catch (Exception ex)
            {
                Console.Error.WriteLine(ex.GetType().FullName + ": " + ex.Message);
                Console.Error.WriteLine(ex.StackTrace ?? "");
                if (!string.IsNullOrWhiteSpace(retainedFixture)) Console.Error.WriteLine("Fixture retained: " + retainedFixture);
                return 1;
            }
            finally
            {
                try { mutex.ReleaseMutex(); }
                catch { }
            }
        }
    }

    private static int RunTargetHelper(string readyPath, string stopPath)
    {
        try
        {
            EnsureParent(readyPath);
            File.WriteAllText(readyPath, DateTime.Now.ToString("o", CultureInfo.InvariantCulture));
            Stopwatch timeout = Stopwatch.StartNew();
            while (timeout.ElapsedMilliseconds < 30000 && !File.Exists(stopPath)) Thread.Sleep(25);
            return File.Exists(stopPath) ? 0 : 2;
        }
        catch
        {
            return 1;
        }
    }

    private static void RunAliasHandoffScenario()
    {
        AssertNoExistingProcess("TslGame");
        AssertNoExistingProcess("TslGame-Win64-Shipping");

        string testRoot = AppDomain.CurrentDomain.BaseDirectory;
        string root = Path.GetFullPath(Path.Combine(testRoot, ".."));
        string fixture = Path.Combine(Path.GetTempPath(), "framescope-target-lifecycle-" + Guid.NewGuid().ToString("N"));
        retainedFixture = fixture;
        string dataRoot = Path.Combine(fixture, "runs");
        string toolsDir = Path.Combine(fixture, "tools");
        Directory.CreateDirectory(dataRoot);
        Directory.CreateDirectory(toolsDir);

        CopyRuntime(root, fixture);
        string testExe = Path.Combine(testRoot, "FrameScopeTargetLifecycleIntegrationTests.exe");
        string targetAExe = Path.Combine(fixture, "TslGame.exe");
        string targetBExe = Path.Combine(fixture, "TslGame-Win64-Shipping.exe");
        File.Copy(testExe, targetAExe, true);
        File.Copy(testExe, targetBExe, true);
        File.Copy(Path.Combine(testRoot, "FrameScopePubgFakePresentMon.exe"), Path.Combine(toolsDir, "PresentMon-2.4.1-x64.exe"), true);

        string configPath = Path.Combine(fixture, "framescope-integration-config.json");
        FrameScopeConfigStore.Save(configPath, new FrameScopeConfig
        {
            PollIntervalMs = FrameScopeConfigStore.InternalPollIntervalMs,
            TelemetrySampleIntervalMs = 500,
            DataRoot = dataRoot,
            OpenReportOnComplete = false,
            AutoGenerateDiagnosticReport = false,
            MonitorScript = FrameScopeConfigStore.NativeMonitorMode,
            CpuTelemetry = new FrameScopeCpuTelemetryConfig
            {
                CollectPerCoreFrequency = false,
                CollectCpuVoltage = false,
                VoltageProvider = "disabled"
            },
            Targets = new List<FrameScopeTarget>
            {
                new FrameScopeTarget
                {
                    Enabled = true,
                    Name = "PUBG Alias Lifecycle Integration",
                    ProcessName = "TslGame.exe",
                    OpenReportOnComplete = false
                }
            }
        });

        string aReady = Path.Combine(fixture, "a.ready");
        string aStop = Path.Combine(fixture, "a.stop");
        string bReady = Path.Combine(fixture, "b.ready");
        string bStop = Path.Combine(fixture, "b.stop");
        Process targetA = null;
        Process targetB = null;
        Process watcher = null;
        int monitorPid = 0;
        string runDir = "";
        bool passed = false;

        try
        {
            targetA = StartHidden(targetAExe, JoinArguments("--helper-ready", aReady, "--helper-stop", aStop), fixture);
            WaitUntil(delegate { return File.Exists(aReady); }, 5000, "primary alias ready");

            watcher = StartHidden(
                Path.Combine(fixture, "FrameScopeMonitor.exe"),
                JoinArguments("--watcher", "--config", configPath, "--exit-after-first-run"),
                fixture);

            string watcherState = Path.Combine(fixture, "framescope-watcher-state.json");
            WaitUntil(delegate
            {
                monitorPid = TryReadMonitorPid(watcherState);
                return monitorPid > 0;
            }, 15000, "watcher active monitor PID");

            WaitUntil(delegate
            {
                runDir = FindRunDirectory(dataRoot);
                if (string.IsNullOrWhiteSpace(runDir)) return false;
                return CountValidCsvRows(Path.Combine(runDir, "process-samples.csv"), 11) > 0 &&
                    CountValidCsvRows(Path.Combine(runDir, "system-samples.csv"), 21) > 0;
            }, 15000, "initial process and system samples");

            File.WriteAllText(aStop, "stop");
            AssertTrue(targetA.WaitForExit(5000), "primary alias exits");
            DateTime primaryExitedAt = DateTime.Now;

            Thread.Sleep(600);
            AssertTrue(IsProcessRunning(monitorPid), "monitor survives the A-to-B alias gap");
            AssertTrue(!watcher.HasExited, "watcher remains active during alias gap");

            targetB = StartHidden(targetBExe, JoinArguments("--helper-ready", bReady, "--helper-stop", bStop), fixture);
            WaitUntil(delegate { return File.Exists(bReady); }, 5000, "replacement alias ready");
            WaitUntil(delegate { return CsvContains(Path.Combine(runDir, "process-samples.csv"), "TslGame-Win64-Shipping"); }, 7000, "process CSV records replacement alias");

            int processRowsAfterHandoff = CountValidCsvRows(Path.Combine(runDir, "process-samples.csv"), 11);
            int systemRowsAfterHandoff = CountValidCsvRows(Path.Combine(runDir, "system-samples.csv"), 21);
            WaitUntil(delegate
            {
                return CountValidCsvRows(Path.Combine(runDir, "process-samples.csv"), 11) > processRowsAfterHandoff &&
                    CountValidCsvRows(Path.Combine(runDir, "system-samples.csv"), 21) > systemRowsAfterHandoff;
            }, 6000, "sampler CSV rows continue increasing while replacement alias lives");
            AssertTrue(IsProcessRunning(monitorPid), "same monitor remains active for replacement alias");

            File.WriteAllText(bStop, "stop");
            AssertTrue(targetB.WaitForExit(5000), "replacement alias exits");
            DateTime replacementExitedAt = DateTime.Now;
            Thread.Sleep(1000);
            AssertTrue(IsProcessRunning(monitorPid), "monitor honors the bounded quiescence window");

            Stopwatch finalExit = Stopwatch.StartNew();
            WaitUntil(delegate { return !IsProcessRunning(monitorPid); }, 8000, "monitor exits after replacement alias quiescence");
            finalExit.Stop();
            AssertTrue(finalExit.ElapsedMilliseconds >= 700, "monitor does not skip remaining quiescence");
            AssertTrue(finalExit.ElapsedMilliseconds <= 8000, "monitor true-exit delay remains bounded");

            AssertTrue(watcher.WaitForExit(30000), "watcher exits after report completion");
            AssertEqual(0, watcher.ExitCode, "watcher exit code");
            AssertEqual(1, FindRunDirectories(dataRoot).Length, "one monitor run across alias handoff");

            string processCsv = Path.Combine(runDir, "process-samples.csv");
            string systemCsv = Path.Combine(runDir, "system-samples.csv");
            AssertContinuousSampleIndexes(processCsv, 1, "process sampler indexes");
            AssertContinuousSampleIndexes(systemCsv, 1, "system sampler indexes");
            AssertTrue(LatestCsvTimestamp(processCsv) > replacementExitedAt, "process samples extend into post-target quiescence");
            AssertTrue(LatestCsvTimestamp(systemCsv) > replacementExitedAt, "system samples extend into post-target quiescence");
            AssertTrue(primaryExitedAt < replacementExitedAt, "replacement alias outlives primary alias");

            Dictionary<string, object> status = ReadJson(Path.Combine(runDir, "status.json"));
            AssertEqual("done", Convert.ToString(status["Phase"], CultureInfo.InvariantCulture), "final monitor phase");
            AssertEqual(true, Convert.ToBoolean(status["ReportGeneratedByWatcher"], CultureInfo.InvariantCulture), "watcher generated report");
            AssertEqual(0, Convert.ToInt32(status["ReportGenerationExitCode"], CultureInfo.InvariantCulture), "report generator exit code");
            AssertEqual(100, Convert.ToInt32(status["ReportProgressPercent"], CultureInfo.InvariantCulture), "report progress percent");

            AssertNonEmpty(Path.Combine(runDir, "charts", "framescope-interactive-report.html"));
            AssertNonEmpty(Path.Combine(runDir, "charts", "framescope-interactive-data.js"));
            string manifestPath = Path.Combine(runDir, "charts", "framescope-interactive-manifest.json");
            AssertNonEmpty(manifestPath);
            string manifest = File.ReadAllText(manifestPath, Encoding.UTF8);
            AssertTrue(Regex.IsMatch(manifest, "\\\"hasFrameData\\\"\\s*:\\s*true", RegexOptions.IgnoreCase), "report manifest has frame data");
            AssertTrue(Regex.IsMatch(manifest, "\\\"processSamples\\\"\\s*:\\s*[1-9][0-9]*", RegexOptions.IgnoreCase), "report manifest has process samples");
            AssertTrue(Regex.IsMatch(manifest, "\\\"systemSamples\\\"\\s*:\\s*[1-9][0-9]*", RegexOptions.IgnoreCase), "report manifest has system samples");
            string historyPath = Path.Combine(fixture, "framescope-history.jsonl");
            AssertEqual(1, File.ReadAllLines(historyPath).Count(line => !string.IsNullOrWhiteSpace(line)), "one watcher history entry");

            passed = true;
            retainedFixture = "";
        }
        finally
        {
            TrySignal(aStop);
            TrySignal(bStop);
            TryStop(targetA);
            TryStop(targetB);
            TryStop(watcher);
            if (monitorPid > 0) TryStop(monitorPid);
            TryStopPresentMon(runDir);
            if (passed) TryDeleteDirectory(fixture);
        }
    }

    private static void RunOverlappingWatcherClaimScenario()
    {
        const string fooBaseName = "FrameScopeOverlapFoo";
        const string barBaseName = "FrameScopeOverlapBar";
        AssertNoExistingProcess(fooBaseName);
        AssertNoExistingProcess(barBaseName);

        string testRoot = AppDomain.CurrentDomain.BaseDirectory;
        string root = Path.GetFullPath(Path.Combine(testRoot, ".."));
        string fixture = Path.Combine(Path.GetTempPath(), "framescope-overlap-claim-" + Guid.NewGuid().ToString("N"));
        retainedFixture = fixture;
        string dataRoot = Path.Combine(fixture, "runs");
        string toolsDir = Path.Combine(fixture, "tools");
        Directory.CreateDirectory(dataRoot);
        Directory.CreateDirectory(toolsDir);

        CopyRuntime(root, fixture);
        string testExe = Path.Combine(testRoot, "FrameScopeTargetLifecycleIntegrationTests.exe");
        string fooExe = Path.Combine(fixture, fooBaseName + ".exe");
        File.Copy(testExe, fooExe, true);
        File.Copy(Path.Combine(testRoot, "FrameScopePubgFakePresentMon.exe"), Path.Combine(toolsDir, "PresentMon-2.4.1-x64.exe"), true);

        string configPath = Path.Combine(fixture, "framescope-overlap-config.json");
        FrameScopeConfigStore.Save(configPath, new FrameScopeConfig
        {
            PollIntervalMs = FrameScopeConfigStore.InternalPollIntervalMs,
            TelemetrySampleIntervalMs = 500,
            DataRoot = dataRoot,
            OpenReportOnComplete = false,
            AutoGenerateDiagnosticReport = false,
            MonitorScript = FrameScopeConfigStore.NativeMonitorMode,
            CpuTelemetry = new FrameScopeCpuTelemetryConfig
            {
                CollectPerCoreFrequency = false,
                CollectCpuVoltage = false,
                VoltageProvider = "disabled"
            },
            Targets = new List<FrameScopeTarget>
            {
                new FrameScopeTarget
                {
                    Enabled = true,
                    Name = "Overlap Primary",
                    ProcessName = fooBaseName + ".exe",
                    OpenReportOnComplete = false
                },
                new FrameScopeTarget
                {
                    Enabled = true,
                    Name = "Overlap Expanded",
                    ProcessName = fooBaseName + ".exe;" + barBaseName + ".exe",
                    OpenReportOnComplete = false
                }
            }
        });

        string fooReady = Path.Combine(fixture, "foo.ready");
        string fooStop = Path.Combine(fixture, "foo.stop");
        string statePath = Path.Combine(fixture, "framescope-watcher-state.json");
        Process foo = null;
        Process watcher = null;
        List<int> monitorPids = new List<int>();
        bool passed = false;

        try
        {
            foo = StartHidden(fooExe, JoinArguments("--helper-ready", fooReady, "--helper-stop", fooStop), fixture);
            WaitUntil(delegate { return File.Exists(fooReady); }, 5000, "overlap helper ready");
            watcher = StartHidden(
                Path.Combine(fixture, "FrameScopeMonitor.exe"),
                JoinArguments("--watcher", "--config", configPath, "--exit-after-first-run"),
                fixture);

            List<Dictionary<string, object>> active = null;
            WaitUntil(delegate
            {
                active = TryReadActiveMonitors(statePath);
                return active != null && active.Count > 0;
            }, 15000, "overlap watcher active state");
            Thread.Sleep(FrameScopeConfigStore.InternalPollIntervalMs + 300);
            active = TryReadActiveMonitors(statePath);

            AssertTrue(active != null, "overlap watcher state parses");
            AssertEqual(1, active.Count, "overlapping targets claim exactly one active monitor");
            Dictionary<string, object> claimed = active[0];
            string expectedKey = FrameScopeTargetLifecycle.CanonicalBaseNameTargetKey(new[] { fooBaseName });
            AssertEqual(expectedKey, Convert.ToString(claimed["Key"], CultureInfo.InvariantCulture), "overlap state canonical key");
            List<string> aliases = ReadStringList(claimed["Aliases"]);
            AssertEqual(1, aliases.Count, "overlap state claimed alias count");
            AssertEqual(fooBaseName.ToLowerInvariant(), aliases[0], "overlap state normalized alias");

            int monitorPid = Convert.ToInt32(claimed["MonitorPid"], CultureInfo.InvariantCulture);
            monitorPids.Add(monitorPid);
            AssertTrue(IsProcessRunning(monitorPid), "overlap claimed monitor is running");

            TrySignal(fooStop);
            AssertTrue(foo.WaitForExit(5000), "overlap helper exits");
            AssertTrue(watcher.WaitForExit(30000), "overlap watcher exits after one completed run");
            AssertEqual(0, watcher.ExitCode, "overlap watcher exit code");
            AssertEqual(1, FindRunDirectories(dataRoot).Length, "overlapping targets create one run");

            passed = true;
            retainedFixture = "";
        }
        finally
        {
            TrySignal(fooStop);
            TryStop(foo);
            TryStop(watcher);
            foreach (int monitorPid in monitorPids) TryStop(monitorPid);
            foreach (string runDir in FindRunDirectories(dataRoot)) TryStopPresentMon(runDir);
            if (passed) TryDeleteDirectory(fixture);
        }
    }

    private static void CopyRuntime(string root, string fixture)
    {
        string[] executables =
        {
            "FrameScopeMonitor.exe",
            "FrameScopeProcessSampler.exe",
            "FrameScopeSystemSampler.exe",
            "FrameScopeReportGenerator.exe"
        };
        foreach (string name in executables)
        {
            string source = Path.Combine(root, name);
            if (!File.Exists(source)) throw new Exception("Production build output missing: " + source);
            File.Copy(source, Path.Combine(fixture, name), true);
        }
        foreach (string dll in Directory.GetFiles(root, "*.dll", SearchOption.TopDirectoryOnly))
        {
            File.Copy(dll, Path.Combine(fixture, Path.GetFileName(dll)), true);
        }
    }

    private static Process StartHidden(string fileName, string arguments, string workingDirectory)
    {
        Process process = Process.Start(new ProcessStartInfo
        {
            FileName = fileName,
            Arguments = arguments,
            WorkingDirectory = workingDirectory,
            UseShellExecute = false,
            CreateNoWindow = true,
            WindowStyle = ProcessWindowStyle.Hidden
        });
        if (process == null) throw new Exception("Failed to start: " + fileName);
        return process;
    }

    private static string JoinArguments(params string[] values)
    {
        return string.Join(" ", values.Select(Quote).ToArray());
    }

    private static string Quote(string value)
    {
        string text = value ?? "";
        return "\"" + text.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
    }

    private static void WaitUntil(Func<bool> condition, int timeoutMs, string label)
    {
        Stopwatch wait = Stopwatch.StartNew();
        Exception last = null;
        while (wait.ElapsedMilliseconds < timeoutMs)
        {
            try
            {
                if (condition()) return;
                last = null;
            }
            catch (Exception ex)
            {
                last = ex;
            }
            Thread.Sleep(50);
        }
        throw new Exception(label + " timed out after " + timeoutMs + " ms" + (last == null ? "" : ": " + last.Message));
    }

    private static int TryReadMonitorPid(string statePath)
    {
        try
        {
            string text = File.ReadAllText(statePath, Encoding.UTF8);
            Match match = Regex.Match(text, "\\\"MonitorPid\\\"\\s*:\\s*(\\d+)", RegexOptions.IgnoreCase);
            return match.Success ? Int32.Parse(match.Groups[1].Value, CultureInfo.InvariantCulture) : 0;
        }
        catch
        {
            return 0;
        }
    }

    private static List<Dictionary<string, object>> TryReadActiveMonitors(string statePath)
    {
        try
        {
            Dictionary<string, object> state = ReadJson(statePath);
            object value;
            if (!state.TryGetValue("ActiveMonitors", out value)) return null;
            var result = new List<Dictionary<string, object>>();
            IEnumerable items = value as IEnumerable;
            if (items == null) return result;
            foreach (object item in items)
            {
                Dictionary<string, object> monitor = item as Dictionary<string, object>;
                if (monitor != null) result.Add(monitor);
            }
            return result;
        }
        catch
        {
            return null;
        }
    }

    private static List<string> ReadStringList(object value)
    {
        var result = new List<string>();
        IEnumerable items = value as IEnumerable;
        if (items == null || value is string) return result;
        foreach (object item in items) result.Add(Convert.ToString(item, CultureInfo.InvariantCulture));
        return result;
    }

    private static string FindRunDirectory(string dataRoot)
    {
        string[] runs = FindRunDirectories(dataRoot);
        return runs.Length == 0 ? "" : runs.OrderByDescending(Directory.GetLastWriteTimeUtc).First();
    }

    private static string[] FindRunDirectories(string dataRoot)
    {
        if (!Directory.Exists(dataRoot)) return new string[0];
        try
        {
            return Directory.GetFiles(dataRoot, "status.json", SearchOption.AllDirectories)
                .Select(Path.GetDirectoryName)
                .Where(path => !string.IsNullOrWhiteSpace(path))
                .Distinct(StringComparer.OrdinalIgnoreCase)
                .ToArray();
        }
        catch
        {
            return new string[0];
        }
    }

    private static int CountValidCsvRows(string path, int expectedColumns)
    {
        if (!File.Exists(path)) return 0;
        try
        {
            return ReadSharedLines(path)
                .Skip(1)
                .Count(line => !string.IsNullOrWhiteSpace(line) && line.Split(',').Length == expectedColumns);
        }
        catch
        {
            return 0;
        }
    }

    private static bool CsvContains(string path, string value)
    {
        try { return File.Exists(path) && string.Join("\n", ReadSharedLines(path)).IndexOf(value, StringComparison.OrdinalIgnoreCase) >= 0; }
        catch { return false; }
    }

    private static void AssertContinuousSampleIndexes(string path, int column, string label)
    {
        List<int> indexes = new List<int>();
        foreach (string line in ReadSharedLines(path).Skip(1))
        {
            string[] cells = line.Split(',');
            int value;
            if (cells.Length > column && Int32.TryParse(cells[column], NumberStyles.Integer, CultureInfo.InvariantCulture, out value)) indexes.Add(value);
        }
        int[] distinct = indexes.Distinct().OrderBy(value => value).ToArray();
        AssertTrue(distinct.Length >= 3, label + " has multiple samples");
        for (int i = 0; i < distinct.Length; i++) AssertEqual(i, distinct[i], label + " item " + i);
    }

    private static DateTime LatestCsvTimestamp(string path)
    {
        DateTime latest = DateTime.MinValue;
        foreach (string line in ReadSharedLines(path).Skip(1))
        {
            string[] cells = line.Split(',');
            DateTime value;
            if (cells.Length > 0 && DateTime.TryParse(cells[0], CultureInfo.InvariantCulture, DateTimeStyles.RoundtripKind, out value) && value > latest) latest = value;
        }
        return latest;
    }

    private static string[] ReadSharedLines(string path)
    {
        var lines = new List<string>();
        using (var stream = new FileStream(path, FileMode.Open, FileAccess.Read, FileShare.ReadWrite | FileShare.Delete))
        using (var reader = new StreamReader(stream, Encoding.UTF8, true))
        {
            string line;
            while ((line = reader.ReadLine()) != null) lines.Add(line);
        }
        return lines.ToArray();
    }

    private static Dictionary<string, object> ReadJson(string path)
    {
        return Json.Deserialize<Dictionary<string, object>>(File.ReadAllText(path, Encoding.UTF8));
    }

    private static void AssertNonEmpty(string path)
    {
        AssertTrue(File.Exists(path), "file exists: " + path);
        AssertTrue(new FileInfo(path).Length > 0, "file is non-empty: " + path);
    }

    private static bool IsProcessRunning(int pid)
    {
        try
        {
            using (Process process = Process.GetProcessById(pid)) return !process.HasExited;
        }
        catch
        {
            return false;
        }
    }

    private static void AssertNoExistingProcess(string name)
    {
        Process[] processes = Process.GetProcessesByName(name);
        try { AssertEqual(0, processes.Length, "no pre-existing " + name + " process"); }
        finally { foreach (Process process in processes) process.Dispose(); }
    }

    private static void TryStopPresentMon(string runDir)
    {
        if (string.IsNullOrWhiteSpace(runDir)) return;
        try
        {
            Dictionary<string, object> status = ReadJson(Path.Combine(runDir, "status.json"));
            object value;
            if (status.TryGetValue("PresentMonSessionName", out value)) TrySignal(FrameScopePubgSimulationCommon.StopSentinelPath(Convert.ToString(value, CultureInfo.InvariantCulture)));
        }
        catch { }
    }

    private static void TrySignal(string path)
    {
        if (string.IsNullOrWhiteSpace(path)) return;
        try { File.WriteAllText(path, "stop"); }
        catch { }
    }

    private static void TryStop(Process process)
    {
        if (process == null) return;
        try { if (!process.HasExited) process.Kill(); }
        catch { }
        try { process.WaitForExit(3000); }
        catch { }
        try { process.Dispose(); }
        catch { }
    }

    private static void TryStop(int pid)
    {
        try { using (Process process = Process.GetProcessById(pid)) TryStop(process); }
        catch { }
    }

    private static void EnsureParent(string path)
    {
        string parent = Path.GetDirectoryName(Path.GetFullPath(path));
        if (!string.IsNullOrWhiteSpace(parent)) Directory.CreateDirectory(parent);
    }

    private static void TryDeleteDirectory(string path)
    {
        try { Directory.Delete(path, true); }
        catch { }
    }

    private static void AssertEqual<T>(T expected, T actual, string label)
    {
        if (!EqualityComparer<T>.Default.Equals(expected, actual)) throw new Exception(label + ": expected <" + expected + "> but got <" + actual + ">");
    }

    private static void AssertTrue(bool condition, string label)
    {
        if (!condition) throw new Exception(label);
    }
}
