using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.IO;
using System.Globalization;
using System.Linq;
using System.Management;
using System.Text;
using System.Threading;
using System.Web.Script.Serialization;
using System.Windows.Forms;
using Microsoft.Win32;
using System.Runtime.InteropServices;

internal sealed class ActiveMonitor
{
    public FrameScopeTarget Target;
    public Process Process;
    public int MonitorPid;
    public string RunRoot;
    public DateTime StartedAt;
}

internal static partial class FrameScopeNativeMonitor
{
    private static void RunNativeWatcher(string[] args)
    {
        try { Process.GetCurrentProcess().PriorityClass = ProcessPriorityClass.BelowNormal; }
        catch { }

        var configPath = GetArgValue(args, "--config", ConfigPath);
        var exitAfterFirstRun = HasArg(args, "--exit-after-first-run");
        var activeMonitors = new Dictionary<string, ActiveMonitor>(StringComparer.OrdinalIgnoreCase);
        var completedRuns = 0;
        var lastReport = "";
        var lastStateWrite = DateTime.MinValue;
        var lastStateSignature = "";
        var recoveredStaleRuns = false;
        var lastRetentionCleanup = DateTime.MinValue;

        WriteFrameScopeLog("native-watcher-start config=" + configPath);

        while (true)
        {
            var pollStarted = Stopwatch.StartNew();
            var config = LoadConfigFromPath(configPath);
            var dataRoot = ResolveDataRoot(config.DataRoot);
            Directory.CreateDirectory(dataRoot);
            if ((DateTime.Now - lastRetentionCleanup).TotalHours >= 6)
            {
                ThreadPool.QueueUserWorkItem(delegate { try { FrameScopeDiagnostics.ApplyRetentionPolicy(Root, config); } catch { } });
                lastRetentionCleanup = DateTime.Now;
            }
            if (!recoveredStaleRuns)
            {
                RecoverStaleMissingReports(dataRoot);
                recoveredStaleRuns = true;
            }

            foreach (var key in activeMonitors.Keys.ToArray())
            {
                var item = activeMonitors[key];
                if (!MonitorHasExited(item)) continue;

                var run = LatestRunDirectory(item.RunRoot);
                var status = run != null ? ReadStatusDictionary(run.FullName) : null;
                var exitCode = GetMonitorExitCode(item, status);
                if (run != null)
                {
                    status = EnsureReportForCompletedRun(run.FullName, status, exitCode);
                    var entry = AddHistoryEntry(item.Target, run.FullName, status, exitCode);
                    lastReport = entry.ReportHtml ?? "";
                    WriteFrameScopeLog("monitor-complete game=" + item.Target.Name + " report=" + lastReport);
                    if (config.AutoGenerateDiagnosticReport)
                    {
                        FrameScopeDiagnostics.QueueGenerateReport(config, Root, dataRoot, "auto-monitor-complete", run.FullName);
                        WriteFrameScopeLog("diagnostic-report-queued run=" + run.FullName);
                    }
                    if (ShouldOpenReport(item.Target, config) && File.Exists(lastReport) && ShouldAutoOpenCompletedReport(status))
                    {
                        if (TryOpenReport(lastReport, run.FullName))
                        {
                            MarkReportOpened(run.FullName, status);
                        }
                    }
                    else if (ShouldOpenReport(item.Target, config) && File.Exists(lastReport) && !ShouldAutoOpenCompletedReport(status))
                    {
                        WriteFrameScopeLog("report-open-skip diagnostic-or-error report=" + lastReport + " error=" + StatusString(status, "ReportError", ""));
                    }
                    else if (ShouldOpenReport(item.Target, config))
                    {
                        WriteFrameScopeLog("report-open-skip missing=" + lastReport);
                    }
                }
                else
                {
                    WriteFrameScopeLog("monitor-complete-no-run game=" + item.Target.Name);
                }

                DisposeProcess(item.Process);
                activeMonitors.Remove(key);
                completedRuns++;
            }

            foreach (var target in config.Targets.Where(t => t != null && t.Enabled && !string.IsNullOrWhiteSpace(t.ProcessName)))
            {
                var processBases = BuildTargetProcessBaseNames(target.ProcessName, target.Name);
                if (processBases.Count == 0) continue;
                var processBase = processBases[0];
                var key = processBase.ToLowerInvariant();
                if (activeMonitors.ContainsKey(key)) continue;
                var detected = FindBestTargetProcess(processBases, 0);
                WriteVerboseFrameScopeLog(config, "target-scan name=" + target.Name + " aliases=" + string.Join(";", processBases.ToArray()) + " detected=" + (detected == null ? "none" : detected.BaseName + ":" + detected.ProcessId));
                if (detected == null) continue;

                var runRoot = Path.Combine(dataRoot, SafeName(target.Name, processBase));
                Directory.CreateDirectory(runRoot);
                var monitor = StartMonitorProcess(target, runRoot, processBases, detected);
                if (monitor == null) continue;

                activeMonitors[key] = monitor;
                WriteFrameScopeLog("monitor-start game=" + target.Name + " process=" + target.ProcessName + " targetPid=" + detected.ProcessId + " targetBase=" + detected.BaseName + " pid=" + monitor.MonitorPid);
            }

            var phase = activeMonitors.Count > 0 ? "monitoring" : "idle";
            var stateSignature = phase + "|" + completedRuns + "|" + lastReport + "|" + string.Join(",", activeMonitors.Keys.OrderBy(v => v).ToArray());
            var stateIntervalMs = activeMonitors.Count > 0 ? 2000 : 5000;
            var now = DateTime.Now;
            if (stateSignature != lastStateSignature || (now - lastStateWrite).TotalMilliseconds >= stateIntervalMs)
            {
                WriteNativeWatcherState(configPath, phase, activeMonitors, completedRuns, lastReport);
                lastStateWrite = now;
                lastStateSignature = stateSignature;
            }

            if (exitAfterFirstRun && completedRuns >= 1 && activeMonitors.Count == 0)
            {
                WriteFrameScopeLog("native-watcher-exit-after-first-run");
                break;
            }

            var pollMs = config.PollIntervalMs > 0 ? config.PollIntervalMs : 1000;
            if (pollMs < 500) pollMs = 500;
            pollStarted.Stop();
            WritePerformanceFrameScopeLog(config, "watcher-poll-ms=" + pollStarted.ElapsedMilliseconds + " active=" + activeMonitors.Count + " completed=" + completedRuns);
            System.Threading.Thread.Sleep(pollMs);
        }
    }

    private static bool IsProcessRunning(string processBaseName)
    {
        return FindBestTargetProcess(new List<string> { processBaseName }, 0) != null;
    }

    private static bool IsAnyTargetProcessRunning(List<string> processBaseNames)
    {
        return FindBestTargetProcess(processBaseNames, 0) != null;
    }

    private static ActiveMonitor StartMonitorProcess(FrameScopeTarget target, string runRoot, List<string> processBaseNames, TargetProcessSnapshot detected)
    {
        var sampleMs = target.SampleIntervalMs > 0 ? target.SampleIntervalMs : 100;
        var processSampleMs = target.ProcessSampleIntervalMs >= 100 ? target.ProcessSampleIntervalMs : 100;
        var slowSampleMs = target.SlowSampleIntervalMs >= sampleMs ? target.SlowSampleIntervalMs : Math.Max(1000, sampleMs);
        var safeName = SafeName(target.Name, processBaseNames.Count > 0 ? processBaseNames[0] : GetTargetBaseName(target.ProcessName));
        var aliasArg = string.Join(";", processBaseNames.ToArray());
        var args =
            "--monitor-session" +
            " --TargetProcessName " + Quote(target.ProcessName) +
            " --TargetProcessAliases " + Quote(aliasArg) +
            " --TargetDisplayName " + Quote(target.Name) +
            " --InitialTargetPid " + (detected == null ? "0" : detected.ProcessId.ToString(CultureInfo.InvariantCulture)) +
            " --WaitSeconds 15 --CaptureSeconds 0" +
            " --SampleIntervalMs " + sampleMs.ToString(CultureInfo.InvariantCulture) +
            " --ProcessSampleIntervalMs " + processSampleMs.ToString(CultureInfo.InvariantCulture) +
            " --SlowSampleIntervalMs " + slowSampleMs.ToString(CultureInfo.InvariantCulture) +
            " --ControlPollIntervalMs 3000" +
            " --RunRoot " + Quote(runRoot) +
            " --RunNamePrefix " + Quote(safeName);

        try
        {
            var psi = new ProcessStartInfo
            {
                FileName = Application.ExecutablePath,
                Arguments = args,
                WorkingDirectory = Root,
                UseShellExecute = false,
                CreateNoWindow = true,
                WindowStyle = ProcessWindowStyle.Hidden
            };
            var process = Process.Start(psi);
            if (process == null) return null;
            try { process.PriorityClass = ProcessPriorityClass.Idle; }
            catch { }
            return new ActiveMonitor
            {
                Target = target,
                Process = process,
                MonitorPid = process.Id,
                RunRoot = runRoot,
                StartedAt = DateTime.Now
            };
        }
        catch (Exception ex)
        {
            WriteFrameScopeLog("native-monitor-start-failed game=" + target.Name + " error=" + ex.Message);
            return null;
        }
    }

    private static bool MonitorHasExited(ActiveMonitor item)
    {
        if (item == null) return true;
        try
        {
            if (item.Process != null)
            {
                item.Process.Refresh();
                return item.Process.HasExited;
            }
        }
        catch { }

        try
        {
            using (Process.GetProcessById(item.MonitorPid)) { return false; }
        }
        catch
        {
            return true;
        }
    }

    private static int GetMonitorExitCode(ActiveMonitor item, Dictionary<string, object> status)
    {
        try
        {
            if (item != null && item.Process != null) return item.Process.ExitCode;
        }
        catch { }

        object value;
        if (status != null && status.TryGetValue("ExitCode", out value))
        {
            try { return Convert.ToInt32(value); }
            catch { }
        }
        return -1;
    }

    private static void WriteNativeWatcherState(string configPath, string phase, Dictionary<string, ActiveMonitor> activeMonitors, int completedRuns, string lastReport)
    {
        var active = activeMonitors.Values.Select(item => new
        {
            Key = GetTargetBaseName(item.Target.ProcessName).ToLowerInvariant(),
            Game = item.Target.Name,
            ProcessName = item.Target.ProcessName,
            MonitorPid = MonitorHasExited(item) ? (int?)null : item.MonitorPid,
            RunRoot = item.RunRoot
        }).ToArray();

        var state = new
        {
            Time = DateTime.Now.ToString("o"),
            Phase = phase,
            ConfigPath = configPath,
            WatcherPid = Process.GetCurrentProcess().Id,
            WatcherMode = "native",
            CompletedRuns = completedRuns,
            LastReport = lastReport,
            HistoryPath = FrameScopeNativeMonitor.HistoryPath,
            LogPath = Path.Combine(Root, "framescope-watcher.log"),
            ActiveMonitors = active
        };
        File.WriteAllText(StatePath, Json.Serialize(state));
    }

    private static void WriteFrameScopeLog(string message)
    {
        FrameScopeDiagnostics.AppendLogAsync(Path.Combine(Root, "framescope-watcher.log"), message);
    }

    private static void WriteVerboseFrameScopeLog(FrameScopeConfig config, string message)
    {
        if (config != null && config.EnableVerboseLogs) WriteFrameScopeLog("verbose " + message);
    }

    private static void WritePerformanceFrameScopeLog(FrameScopeConfig config, string message)
    {
        if (config != null && config.EnablePerformanceDiagnosticsLogs) WriteFrameScopeLog("perf " + message);
    }
}
