using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.IO;
using System.Globalization;
using System.Linq;
using System.Management;
using System.Text;
using System.Threading;
using System.Web.Script.Serialization;
using System.Windows.Forms;
using Microsoft.Win32;
using System.Runtime.InteropServices;

internal sealed class ActiveMonitor
{
    public FrameScopeTarget Target;
    public Process Process;
    public int MonitorPid;
    public string RunRoot;
    public DateTime StartedAt;
}

internal static partial class FrameScopeNativeMonitor
{
    private static readonly FrameScopeLogRateLimiter VerboseWatcherLogRateLimiter = new FrameScopeLogRateLimiter();
    private static readonly FrameScopeLogRateLimiter PerformanceWatcherLogRateLimiter = new FrameScopeLogRateLimiter();
    private static readonly TimeSpan WatcherTargetScanLogInterval = TimeSpan.FromSeconds(15);
    private static readonly TimeSpan WatcherPerformancePollLogInterval = TimeSpan.FromSeconds(15);

    private static void RunNativeWatcher(string[] args)
    {
        try { Process.GetCurrentProcess().PriorityClass = ProcessPriorityClass.BelowNormal; }
        catch { }

        var configPath = GetArgValue(args, "--config", ConfigPath);
        var exitAfterFirstRun = HasArg(args, "--exit-after-first-run");
        var activeMonitors = new Dictionary<string, ActiveMonitor>(StringComparer.OrdinalIgnoreCase);
        var completedRuns = 0;
        var lastReport = "";
        var lastStateWrite = DateTime.MinValue;
        var lastStateSignature = "";
        var recoveredStaleRuns = false;
        var lastRetentionCleanup = DateTime.MinValue;

        WriteFrameScopeLog("native-watcher-start config=" + configPath);

        while (true)
        {
            var pollStarted = Stopwatch.StartNew();
            var config = LoadConfigFromPath(configPath);
            var dataRoot = ResolveDataRoot(config.DataRoot);
            Directory.CreateDirectory(dataRoot);
            if ((DateTime.Now - lastRetentionCleanup).TotalHours >= 6)
            {
                ThreadPool.QueueUserWorkItem(delegate { try { FrameScopeDiagnostics.ApplyRetentionPolicy(Root, config); } catch { } });
                lastRetentionCleanup = DateTime.Now;
            }
            if (!recoveredStaleRuns)
            {
                RecoverStaleMissingReports(dataRoot, config);
                recoveredStaleRuns = true;
            }

            foreach (var key in activeMonitors.Keys.ToArray())
            {
                var item = activeMonitors[key];
                if (!MonitorHasExited(item)) continue;

                var run = LatestRunDirectory(item.RunRoot);
                var status = run != null ? ReadStatusDictionary(run.FullName) : null;
                var exitCode = GetMonitorExitCode(item, status);
                if (run != null)
                {
                    status = EnsureReportForCompletedRun(run.FullName, status, exitCode, config);
                    var entry = AddHistoryEntry(item.Target, run.FullName, status, exitCode);
                    lastReport = entry.ReportHtml ?? "";
                    WriteFrameScopeLog("monitor-complete game=" + item.Target.Name + " report=" + lastReport);
                    if (config.AutoGenerateDiagnosticReport && FrameScopeLoggingPolicy.ShouldAutoGenerateDiagnosticReport(status, exitCode))
                    {
                        FrameScopeDiagnostics.QueueGenerateReport(config, Root, dataRoot, "auto-monitor-complete", run.FullName);
                        WriteFrameScopeLog("diagnostic-report-queued run=" + run.FullName);
                    }
                    else if (config.AutoGenerateDiagnosticReport)
                    {
                        WriteVerboseFrameScopeLog(config, delegate { return "diagnostic-report-skip healthy-run=" + run.FullName; });
                    }
                    if (ShouldOpenReport(item.Target, config) && File.Exists(lastReport) && ShouldAutoOpenCompletedReport(status))
                    {
                        if (TryOpenReport(lastReport, run.FullName))
                        {
                            MarkReportOpened(run.FullName, status);
                        }
                    }
                    else if (ShouldOpenReport(item.Target, config) && File.Exists(lastReport) && !ShouldAutoOpenCompletedReport(status))
                    {
                        WriteFrameScopeLog("report-open-skip diagnostic-or-error report=" + lastReport + " error=" + StatusString(status, "ReportError", ""));
                    }
                    else if (ShouldOpenReport(item.Target, config))
                    {
                        WriteFrameScopeLog("report-open-skip missing=" + lastReport);
                    }
                }
                else
                {
                    WriteFrameScopeLog("monitor-complete-no-run game=" + item.Target.Name);
                }

                DisposeProcess(item.Process);
                activeMonitors.Remove(key);
                completedRuns++;
            }

            foreach (var target in config.Targets.Where(t => t != null && t.Enabled && !string.IsNullOrWhiteSpace(t.ProcessName)))
            {
                var processBases = BuildTargetProcessBaseNames(target.ProcessName, target.Name);
                if (processBases.Count == 0) continue;
                var processBase = processBases[0];
                var key = processBase.ToLowerInvariant();
                if (activeMonitors.ContainsKey(key)) continue;
                var detected = FindBestTargetProcess(processBases, 0);
                var detectedText = detected == null ? "none" : detected.BaseName + ":" + detected.ProcessId.ToString(CultureInfo.InvariantCulture);
                WriteRateLimitedVerboseFrameScopeLog(
                    config,
                    "target-scan:" + key,
                    detectedText,
                    WatcherTargetScanLogInterval,
                    delegate { return "target-scan name=" + target.Name + " aliases=" + string.Join(";", processBases.ToArray()) + " detected=" + detectedText; });
                if (detected == null) continue;

                var runRoot = Path.Combine(dataRoot, SafeName(target.Name, processBase));
                Directory.CreateDirectory(runRoot);
                var monitor = StartMonitorProcess(config, target, runRoot, processBases, detected);
                if (monitor == null) continue;

                activeMonitors[key] = monitor;
                WriteFrameScopeLog("monitor-start game=" + target.Name + " process=" + target.ProcessName + " targetPid=" + detected.ProcessId + " targetBase=" + detected.BaseName + " pid=" + monitor.MonitorPid);
            }

            var phase = activeMonitors.Count > 0 ? "monitoring" : "idle";
            var stateSignature = phase + "|" + completedRuns + "|" + lastReport + "|" + string.Join(",", activeMonitors.Keys.OrderBy(v => v).ToArray());
            var stateIntervalMs = activeMonitors.Count > 0 ? 2000 : 5000;
            var now = DateTime.Now;
            if (stateSignature != lastStateSignature || (now - lastStateWrite).TotalMilliseconds >= stateIntervalMs)
            {
                WriteNativeWatcherState(configPath, phase, activeMonitors, completedRuns, lastReport);
                lastStateWrite = now;
                lastStateSignature = stateSignature;
            }

            if (exitAfterFirstRun && completedRuns >= 1 && activeMonitors.Count == 0)
            {
                WriteFrameScopeLog("native-watcher-exit-after-first-run");
                break;
            }

            pollStarted.Stop();
            long watcherPollMs = pollStarted.ElapsedMilliseconds;
            string watcherPollState = "active=" + activeMonitors.Count.ToString(CultureInfo.InvariantCulture) +
                "|completed=" + completedRuns.ToString(CultureInfo.InvariantCulture) +
                "|slow=" + (watcherPollMs >= 100 ? "1" : "0");
            WriteRateLimitedPerformanceFrameScopeLog(
                config,
                "watcher-poll",
                watcherPollState,
                WatcherPerformancePollLogInterval,
                delegate
                {
                    return "watcher-poll-ms=" + watcherPollMs.ToString(CultureInfo.InvariantCulture) +
                        " interval=" + FrameScopeConfigStore.InternalPollIntervalMs.ToString(CultureInfo.InvariantCulture) +
                        " active=" + activeMonitors.Count.ToString(CultureInfo.InvariantCulture) +
                        " completed=" + completedRuns.ToString(CultureInfo.InvariantCulture);
                });
            System.Threading.Thread.Sleep(FrameScopeConfigStore.InternalPollIntervalMs);
        }
    }

    private static bool IsProcessRunning(string processBaseName)
    {
        return FindBestTargetProcess(new List<string> { processBaseName }, 0) != null;
    }

    private static bool IsAnyTargetProcessRunning(List<string> processBaseNames)
    {
        return FindBestTargetProcess(processBaseNames, 0) != null;
    }

    private static ActiveMonitor StartMonitorProcess(FrameScopeConfig config, FrameScopeTarget target, string runRoot, List<string> processBaseNames, TargetProcessSnapshot detected)
    {
        var telemetrySampleMs = config != null && config.TelemetrySampleIntervalMs > 0
            ? config.TelemetrySampleIntervalMs
            : FrameScopeConfigStore.DefaultTelemetrySampleIntervalMs;
        if (telemetrySampleMs < FrameScopeConfigStore.TelemetrySampleIntervalMinMs) telemetrySampleMs = FrameScopeConfigStore.TelemetrySampleIntervalMinMs;
        if (telemetrySampleMs > FrameScopeConfigStore.TelemetrySampleIntervalMaxMs) telemetrySampleMs = FrameScopeConfigStore.TelemetrySampleIntervalMaxMs;
        var sampleMs = telemetrySampleMs;
        var processSampleMs = telemetrySampleMs;
        var slowSampleMs = telemetrySampleMs;
        var cpuCoreTelemetry = config == null ? null : config.CpuTelemetry;
        var enableCpuCoreTelemetry = cpuCoreTelemetry != null && cpuCoreTelemetry.CollectPerCoreFrequency;
        var enableCpuVoltageTelemetry = true;
        var enableCpuVidTelemetry = true;
        var cpuCoreSampleMs = telemetrySampleMs;
        var cpuVoltageSampleMs = telemetrySampleMs;
        var cpuVoltageProvider = "auto";
        var cpuVidSampleMs = telemetrySampleMs;
        var cpuVidProvider = "auto";
        var safeName = SafeName(target.Name, processBaseNames.Count > 0 ? processBaseNames[0] : GetTargetBaseName(target.ProcessName));
        var aliasArg = string.Join(";", processBaseNames.ToArray());
        var args =
            "--monitor-session" +
            " --TargetProcessName " + Quote(target.ProcessName) +
            " --TargetProcessAliases " + Quote(aliasArg) +
            " --TargetDisplayName " + Quote(target.Name) +
            " --InitialTargetPid " + (detected == null ? "0" : detected.ProcessId.ToString(CultureInfo.InvariantCulture)) +
            " --WaitSeconds 15 --CaptureSeconds 0" +
            " --SampleIntervalMs " + sampleMs.ToString(CultureInfo.InvariantCulture) +
            " --ProcessSampleIntervalMs " + processSampleMs.ToString(CultureInfo.InvariantCulture) +
            " --SlowSampleIntervalMs " + slowSampleMs.ToString(CultureInfo.InvariantCulture) +
            " --EnableCpuCoreTelemetry " + (enableCpuCoreTelemetry ? "true" : "false") +
            " --CpuCoreSampleIntervalMs " + cpuCoreSampleMs.ToString(CultureInfo.InvariantCulture) +
            " --EnableCpuVoltageTelemetry " + (enableCpuVoltageTelemetry ? "true" : "false") +
            " --CpuVoltageSampleIntervalMs " + cpuVoltageSampleMs.ToString(CultureInfo.InvariantCulture) +
            " --CpuVoltageProvider " + Quote(cpuVoltageProvider) +
            " --EnableCpuVidTelemetry " + (enableCpuVidTelemetry ? "true" : "false") +
            " --CpuVidSampleIntervalMs " + cpuVidSampleMs.ToString(CultureInfo.InvariantCulture) +
            " --CpuVidProvider " + Quote(cpuVidProvider) +
            " --MonitorProcessRole monitor-session-worker" +
            " --EnableVerboseLogs " + (FrameScopeLoggingPolicy.IsVerboseEnabled(config) ? "true" : "false") +
            " --EnablePerformanceDiagnosticsLogs " + (FrameScopeLoggingPolicy.IsPerformanceDiagnosticsEnabled(config) ? "true" : "false") +
            " --ControlPollIntervalMs 3000" +
            " --RunRoot " + Quote(runRoot) +
            " --RunNamePrefix " + Quote(safeName);

        WriteVerboseFrameScopeLog(config, delegate
        {
            return "monitor-process-args target=" + target.Name +
                " telemetrySampleMs=" + telemetrySampleMs.ToString(CultureInfo.InvariantCulture) +
                " sampleMs=" + sampleMs.ToString(CultureInfo.InvariantCulture) +
                " processSampleMs=" + processSampleMs.ToString(CultureInfo.InvariantCulture) +
                " slowSampleMs=" + slowSampleMs.ToString(CultureInfo.InvariantCulture) +
                " cpuCore=" + enableCpuCoreTelemetry +
                " cpuVoltage=" + enableCpuVoltageTelemetry +
                " cpuVid=" + enableCpuVidTelemetry;
        });

        try
        {
            var psi = new ProcessStartInfo
            {
                FileName = Application.ExecutablePath,
                Arguments = args,
                WorkingDirectory = Root,
                UseShellExecute = false,
                CreateNoWindow = true,
                WindowStyle = ProcessWindowStyle.Hidden
            };
            var process = Process.Start(psi);
            if (process == null) return null;
            try { process.PriorityClass = ProcessPriorityClass.Idle; }
            catch { }
            WriteFrameScopeLog("monitor-worker-start role=monitor-session-worker process=FrameScopeMonitor.exe game=" + target.Name + " pid=" + process.Id.ToString(CultureInfo.InvariantCulture));
            return new ActiveMonitor
            {
                Target = target,
                Process = process,
                MonitorPid = process.Id,
                RunRoot = runRoot,
                StartedAt = DateTime.Now
            };
        }
        catch (Exception ex)
        {
            WriteFrameScopeLog("native-monitor-start-failed game=" + target.Name + " error=" + ex.Message);
            return null;
        }
    }

    private static bool MonitorHasExited(ActiveMonitor item)
    {
        if (item == null) return true;
        try
        {
            if (item.Process != null)
            {
                item.Process.Refresh();
                return item.Process.HasExited;
            }
        }
        catch { }

        try
        {
            using (Process.GetProcessById(item.MonitorPid)) { return false; }
        }
        catch
        {
            return true;
        }
    }

    private static int GetMonitorExitCode(ActiveMonitor item, Dictionary<string, object> status)
    {
        try
        {
            if (item != null && item.Process != null) return item.Process.ExitCode;
        }
        catch { }

        object value;
        if (status != null && status.TryGetValue("ExitCode", out value))
        {
            try { return Convert.ToInt32(value); }
            catch { }
        }
        return -1;
    }

    private static void WriteNativeWatcherState(string configPath, string phase, Dictionary<string, ActiveMonitor> activeMonitors, int completedRuns, string lastReport)
    {
        var active = activeMonitors.Values.Select(item => new
        {
            Key = GetTargetBaseName(item.Target.ProcessName).ToLowerInvariant(),
            Game = item.Target.Name,
            ProcessName = item.Target.ProcessName,
            WorkerRole = "monitor-session-worker",
            WorkerProcessName = "FrameScopeMonitor.exe",
            WorkerExplanation = "任务管理器中可能显示一个 FrameScopeMonitor.exe 子进程，这是监控 worker，不是重复打开软件。",
            MonitorPid = MonitorHasExited(item) ? (int?)null : item.MonitorPid,
            RunRoot = item.RunRoot
        }).ToArray();

        var state = new
        {
            Time = DateTime.Now.ToString("o"),
            Phase = phase,
            ConfigPath = configPath,
            WatcherPid = Process.GetCurrentProcess().Id,
            WatcherMode = "native",
            CompletedRuns = completedRuns,
            LastReport = lastReport,
            HistoryPath = FrameScopeNativeMonitor.HistoryPath,
            LogPath = Path.Combine(Root, "framescope-watcher.log"),
            ActiveMonitors = active
        };
        File.WriteAllText(StatePath, Json.Serialize(state));
    }

    private static void WriteFrameScopeLog(string message)
    {
        FrameScopeDiagnostics.AppendLogAsync(Path.Combine(Root, "framescope-watcher.log"), message);
    }

    private static void WriteVerboseFrameScopeLog(FrameScopeConfig config, string message)
    {
        WriteVerboseFrameScopeLog(FrameScopeLoggingPolicy.IsVerboseEnabled(config), message);
    }

    private static void WriteVerboseFrameScopeLog(FrameScopeConfig config, Func<string> messageFactory)
    {
        WriteVerboseFrameScopeLog(FrameScopeLoggingPolicy.IsVerboseEnabled(config), messageFactory);
    }

    private static void WriteVerboseFrameScopeLog(bool enabled, string message)
    {
        if (enabled) WriteFrameScopeLog("verbose " + message);
    }

    private static void WriteVerboseFrameScopeLog(bool enabled, Func<string> messageFactory)
    {
        if (!enabled || messageFactory == null) return;
        WriteFrameScopeLog("verbose " + (messageFactory() ?? ""));
    }

    private static void WriteRateLimitedVerboseFrameScopeLog(FrameScopeConfig config, string key, string state, TimeSpan minInterval, Func<string> messageFactory)
    {
        if (!FrameScopeLoggingPolicy.IsVerboseEnabled(config)) return;
        if (!VerboseWatcherLogRateLimiter.ShouldWrite(key, state, DateTime.UtcNow, minInterval)) return;
        WriteVerboseFrameScopeLog(true, messageFactory);
    }

    private static void WritePerformanceFrameScopeLog(FrameScopeConfig config, string message)
    {
        WritePerformanceFrameScopeLog(FrameScopeLoggingPolicy.IsPerformanceDiagnosticsEnabled(config), message);
    }

    private static void WritePerformanceFrameScopeLog(FrameScopeConfig config, Func<string> messageFactory)
    {
        WritePerformanceFrameScopeLog(FrameScopeLoggingPolicy.IsPerformanceDiagnosticsEnabled(config), messageFactory);
    }

    private static void WritePerformanceFrameScopeLog(bool enabled, string message)
    {
        if (enabled) WriteFrameScopeLog("perf " + message);
    }

    private static void WritePerformanceFrameScopeLog(bool enabled, Func<string> messageFactory)
    {
        if (!enabled || messageFactory == null) return;
        WriteFrameScopeLog("perf " + (messageFactory() ?? ""));
    }

    private static void WriteRateLimitedPerformanceFrameScopeLog(FrameScopeConfig config, string key, string state, TimeSpan minInterval, Func<string> messageFactory)
    {
        if (!FrameScopeLoggingPolicy.IsPerformanceDiagnosticsEnabled(config)) return;
        if (!PerformanceWatcherLogRateLimiter.ShouldWrite(key, state, DateTime.UtcNow, minInterval)) return;
        WritePerformanceFrameScopeLog(true, messageFactory);
    }
}
