using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.IO;
using System.Globalization;
using System.Linq;
using System.Management;
using System.Text;
using System.Threading;
using System.Web.Script.Serialization;
using System.Windows.Forms;
using Microsoft.Win32;
using System.Runtime.InteropServices;

internal static partial class FrameScopeNativeMonitor
{
    private static Control BuildSettingsPage(FrameScopeConfig config)
    {
        var root = new TableLayoutPanel { Dock = DockStyle.Fill, BackColor = Color.FromArgb(4, 12, 24), ColumnCount = 2, RowCount = 1 };
        root.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 64));
        root.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 36));
        var settings = SectionPanel("设置", "配置监控、报告与诊断行为，保存后立即生效。", 1);
        settings.Margin = new Padding(0, 0, 12, 0);
        settings.Controls.Add(SettingsEditor(config), 0, 1);
        root.Controls.Add(settings, 0, 0);
        var side = new TableLayoutPanel { Dock = DockStyle.Fill, BackColor = root.BackColor, ColumnCount = 1, RowCount = 3 };
        side.RowStyles.Add(new RowStyle(SizeType.Percent, 34));
        side.RowStyles.Add(new RowStyle(SizeType.Percent, 26));
        side.RowStyles.Add(new RowStyle(SizeType.Percent, 40));
        side.Controls.Add(ConfigSummaryCard(config), 0, 0);
        side.Controls.Add(InfoCard("目标状态", EnabledTargetCount(config).ToString(CultureInfo.InvariantCulture) + " / " + (config.Targets == null ? 0 : config.Targets.Count).ToString(CultureInfo.InvariantCulture), "已启用"), 0, 1);
        side.Controls.Add(CaptureChainCard("捕获链状态", "状态：就绪"), 0, 2);
        root.Controls.Add(side, 1, 0);
        return root;
    }

    private static Control SettingsEditor(FrameScopeConfig config)
    {
        var layout = new TableLayoutPanel { Dock = DockStyle.Fill, BackColor = Color.FromArgb(8, 24, 42), Padding = new Padding(22, 14, 22, 18), ColumnCount = 1, RowCount = 12 };
        layout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100));
        layout.RowStyles.Add(new RowStyle(SizeType.Absolute, 30));
        layout.RowStyles.Add(new RowStyle(SizeType.Absolute, 62));
        layout.RowStyles.Add(new RowStyle(SizeType.Absolute, 42));
        layout.RowStyles.Add(new RowStyle(SizeType.Absolute, 30));
        layout.RowStyles.Add(new RowStyle(SizeType.Absolute, 42));
        layout.RowStyles.Add(new RowStyle(SizeType.Absolute, 42));
        layout.RowStyles.Add(new RowStyle(SizeType.Absolute, 30));
        layout.RowStyles.Add(new RowStyle(SizeType.Absolute, 42));
        layout.RowStyles.Add(new RowStyle(SizeType.Absolute, 76));
        layout.RowStyles.Add(new RowStyle(SizeType.Absolute, 78));
        layout.RowStyles.Add(new RowStyle(SizeType.Percent, 100));
        layout.RowStyles.Add(new RowStyle(SizeType.Absolute, 56));

        layout.Controls.Add(SettingsGroupLabel("监测设置"), 0, 0);
        var sampleHost = RoundedInputHost(DefaultSampleIntervalText(config).Replace(" ms", ""), out settingsSampleIntervalText);
        layout.Controls.Add(SettingsRow("采样间隔", "单位 ms，保存后同步到当前目标采样配置。", sampleHost), 0, 1);
        autoOpenCheck = new CheckBox { Checked = config.OpenReportOnComplete };
        layout.Controls.Add(SettingsToggleButton("监测结束后自动打开报告", autoOpenCheck), 0, 2);

        layout.Controls.Add(SettingsGroupLabel("报告设置"), 0, 3);
        autoDiagnosticReportCheck = new CheckBox { Checked = config.AutoGenerateDiagnosticReport };
        layout.Controls.Add(SettingsToggleButton("自动生成诊断报告", autoDiagnosticReportCheck), 0, 4);
        verboseLogCheck = new CheckBox { Checked = config.EnableVerboseLogs };
        layout.Controls.Add(SettingsToggleButton("详细日志", verboseLogCheck), 0, 5);

        layout.Controls.Add(SettingsGroupLabel("诊断设置"), 0, 6);
        performanceDiagnosticsCheck = new CheckBox { Checked = config.EnablePerformanceDiagnosticsLogs };
        layout.Controls.Add(SettingsToggleButton("性能诊断", performanceDiagnosticsCheck), 0, 7);

        var limits = new TableLayoutPanel { Dock = DockStyle.Fill, BackColor = Color.Transparent, ColumnCount = 3, RowCount = 2, Margin = new Padding(0) };
        limits.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50));
        limits.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 18));
        limits.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50));
        limits.RowStyles.Add(new RowStyle(SizeType.Absolute, 22));
        limits.RowStyles.Add(new RowStyle(SizeType.Percent, 100));
        limits.Controls.Add(FormLabel("保留天数"), 0, 0);
        limits.Controls.Add(FormLabel("最大 MB"), 2, 0);
        limits.Controls.Add(RoundedInputHost(config.LogRetentionDays.ToString(CultureInfo.InvariantCulture), out logRetentionDaysText), 0, 1);
        limits.Controls.Add(RoundedInputHost(config.MaxLogDiskMb.ToString(CultureInfo.InvariantCulture), out maxLogDiskMbText), 2, 1);
        layout.Controls.Add(SettingsRow("日志保留", "控制日志与诊断文件占用空间。", limits), 0, 8);

        var dataRoot = new TableLayoutPanel { Dock = DockStyle.Fill, BackColor = Color.Transparent, ColumnCount = 2, RowCount = 1, Margin = new Padding(0) };
        dataRoot.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100));
        dataRoot.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 132));
        dataRoot.Controls.Add(RoundedInputHost(config.DataRoot, out dataRootText), 0, 0);
        var browse = SettingsSmallButton("选择目录", "secondary");
        browse.Dock = DockStyle.None;
        browse.Size = new Size(116, UiControlHeight);
        browse.Margin = new Padding(0);
        var browseHost = new Panel { Dock = DockStyle.Fill, BackColor = Color.Transparent, Margin = new Padding(10, 0, 0, 0) };
        browseHost.Resize += delegate
        {
            browse.Bounds = new Rectangle(
                Math.Max(0, browseHost.ClientSize.Width - browse.Width),
                Math.Max(0, (browseHost.ClientSize.Height - browse.Height) / 2),
                browse.Width,
                browse.Height);
        };
        browse.Click += (_, __) => BrowseDataRoot();
        browseHost.Controls.Add(browse);
        dataRoot.Controls.Add(browseHost, 1, 0);
        layout.Controls.Add(SettingsRow("数据目录", "监测数据、日志和报告的写入位置。", dataRoot), 0, 9);

        var buttonRow = new FlowLayoutPanel
        {
            Dock = DockStyle.Fill,
            FlowDirection = FlowDirection.RightToLeft,
            WrapContents = false,
            BackColor = layout.BackColor,
            Padding = new Padding(0, 10, 0, 0)
        };
        var save = SettingsSmallButton("保存设置", "primary"); save.Click += (_, __) => SaveConfigFromGrid();
        var reset = SettingsSmallButton("恢复默认", "secondary"); reset.Click += (_, __) => ResetConfigToDefaultsFromUi();
        buttonRow.Controls.Add(save);
        buttonRow.Controls.Add(reset);
        layout.Controls.Add(new Panel { Dock = DockStyle.Fill, BackColor = Color.Transparent }, 0, 10);
        layout.Controls.Add(buttonRow, 0, 11);
        return layout;
    }

    private static Control ConfigSummaryCard(FrameScopeConfig config)
    {
        return InfoCard("配置摘要",
            "监测间隔：" + DefaultSampleIntervalText(config) + "\r\n自动打开报告：" + (config.OpenReportOnComplete ? "已启用" : "关闭") + "\r\n详细日志：" + (config.EnableVerboseLogs ? "已启用" : "关闭") + "\r\n性能诊断：" + (config.EnablePerformanceDiagnosticsLogs ? "已启用" : "关闭"),
            "数据目录：" + (Directory.Exists(ResolveDataRoot(config.DataRoot)) ? "可用" : "未创建"));
    }

    private static Label SettingsGroupLabel(string text)
    {
        return new Label
        {
            Text = text,
            Dock = DockStyle.Fill,
            ForeColor = UiCyan,
            Font = new Font("Microsoft YaHei UI", 10.5f, FontStyle.Bold),
            TextAlign = ContentAlignment.MiddleLeft,
            Padding = new Padding(2, 2, 0, 0)
        };
    }

    private static FrameScopeToggleCheckBox ToggleCheck(string text, bool isChecked)
    {
        return new FrameScopeToggleCheckBox
        {
            Text = text,
            Checked = isChecked,
            Dock = DockStyle.Fill,
            BackColor = Color.Transparent,
            Accent = UiCyan,
            TextColor = UiText,
            MutedColor = UiMuted
        };
    }

    private static Control SettingsToggleButton(string text, CheckBox backing)
    {
        var check = ToggleCheck(text, backing != null && backing.Checked);
        check.Margin = new Padding(0, 5, 0, 5);
        check.BackColor = Color.Transparent;
        check.CheckedChanged += delegate
        {
            if (backing != null && backing.Checked != check.Checked)
            {
                backing.Checked = check.Checked;
            }
        };
        if (backing != null)
        {
            backing.CheckedChanged += delegate
            {
                if (check.Checked != backing.Checked)
                {
                    check.Checked = backing.Checked;
                }
            };
        }
        return check;
    }

    private static Control SettingsRow(string title, string subtitle, Control content)
    {
        var row = new TableLayoutPanel
        {
            Dock = DockStyle.Fill,
            Margin = new Padding(0, 0, 0, 6),
            Padding = new Padding(0),
            BackColor = Color.Transparent,
            ColumnCount = 2,
            RowCount = 1
        };
        row.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 300));
        row.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100));

        var labels = new TableLayoutPanel
        {
            Dock = DockStyle.Fill,
            BackColor = Color.Transparent,
            ColumnCount = 1,
            RowCount = 2,
            Padding = new Padding(0, 0, 18, 0)
        };
        labels.RowStyles.Add(new RowStyle(SizeType.Absolute, 24));
        labels.RowStyles.Add(new RowStyle(SizeType.Percent, 100));
        labels.Controls.Add(new Label
        {
            Text = title,
            Dock = DockStyle.Fill,
            BackColor = Color.Transparent,
            ForeColor = UiText,
            Font = new Font("Microsoft YaHei UI", 10.2f, FontStyle.Regular),
            TextAlign = ContentAlignment.MiddleLeft
        }, 0, 0);
        labels.Controls.Add(new Label
        {
            Text = subtitle,
            Dock = DockStyle.Fill,
            BackColor = Color.Transparent,
            ForeColor = UiMuted,
            Font = new Font("Microsoft YaHei UI", 8.5f),
            TextAlign = ContentAlignment.TopLeft,
            AutoEllipsis = true
        }, 0, 1);
        row.Controls.Add(labels, 0, 0);

        if (content != null)
        {
            content.Dock = DockStyle.Fill;
            content.Margin = new Padding(0, 5, 0, 5);
            row.Controls.Add(content, 1, 0);
        }
        return row;
    }

    private static TextBox DarkTextBox(string text)
    {
        var box = new TextBox
        {
            Text = text,
            Dock = DockStyle.Fill,
            BackColor = Color.FromArgb(12, 40, 64),
            ForeColor = UiText,
            BorderStyle = BorderStyle.None,
            Margin = new Padding(0, 6, 6, 6),
            Font = new Font("Microsoft YaHei UI", 9f)
        };
        MakeRounded(box, UiRadiusControl);
        return box;
    }

    private static Control RoundedInputHost(string text, out TextBox box)
    {
        var textBox = new TextBox
        {
            Text = text,
            Dock = DockStyle.Fill,
            BackColor = Color.FromArgb(12, 40, 64),
            ForeColor = UiText,
            BorderStyle = BorderStyle.FixedSingle,
            Font = new Font("Microsoft YaHei UI", 9.4f),
            Margin = new Padding(0, 7, 0, 7)
        };
        var tooltip = new ToolTip { AutomaticDelay = 120, AutoPopDelay = 12000 };
        textBox.HandleCreated += delegate
        {
            if (textBox.TextLength > 0)
            {
                textBox.SelectionStart = textBox.TextLength;
                textBox.ScrollToCaret();
            }
        };
        tooltip.SetToolTip(textBox, text ?? "");
        MakeRounded(textBox, UiRadiusControl);
        box = textBox;
        return textBox;
    }
}
