using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.IO;
using System.Globalization;
using System.Linq;
using System.Management;
using System.Text;
using System.Threading;
using System.Web.Script.Serialization;
using System.Windows.Forms;
using Microsoft.Win32;
using System.Runtime.InteropServices;

internal static partial class FrameScopeNativeMonitor
{
    private static void AttachConfigDirtyFeedback(string pageKey)
    {
        if (!string.Equals(pageKey, "settings", StringComparison.OrdinalIgnoreCase) &&
            !string.Equals(pageKey, "targets", StringComparison.OrdinalIgnoreCase))
        {
            return;
        }

        EventHandler changed = (_, __) => SetConfigDirtyStatus();
        if (autoOpenCheck != null) autoOpenCheck.CheckedChanged += changed;
        if (verboseLogCheck != null) verboseLogCheck.CheckedChanged += changed;
        if (performanceDiagnosticsCheck != null) performanceDiagnosticsCheck.CheckedChanged += changed;
        if (autoDiagnosticReportCheck != null) autoDiagnosticReportCheck.CheckedChanged += changed;
        if (settingsSampleIntervalText != null) settingsSampleIntervalText.TextChanged += changed;
        if (logRetentionDaysText != null) logRetentionDaysText.TextChanged += changed;
        if (maxLogDiskMbText != null) maxLogDiskMbText.TextChanged += changed;
        if (dataRootText != null) dataRootText.TextChanged += changed;
        if (grid != null)
        {
            grid.CellValueChanged += (_, e) =>
            {
                if (e.RowIndex >= 0) SetConfigDirtyStatus();
            };
        }
    }

    private static void SetConfigDirtyStatus()
    {
        SetStatus("设置已修改，点击保存设置生效。");
    }

    private static FrameScopeConfig ReadGridConfig()
    {
        var existing = LoadConfig();
        var targets = new List<FrameScopeTarget>();
        if (grid == null)
        {
            if (existing.Targets != null) targets.AddRange(existing.Targets);
        }
        else
        {
            foreach (DataGridViewRow row in grid.Rows)
            {
                if (row.IsNewRow) continue;
                var processName = Convert.ToString(row.Cells["ProcessName"].Value) ?? "";
                if (string.IsNullOrWhiteSpace(processName)) continue;
                processName = FrameScopeTargetEditRules.NormalizeProcessName(processName);
                if (string.IsNullOrWhiteSpace(processName)) continue;
                var name = Convert.ToString(row.Cells["GameName"].Value);
                if (string.IsNullOrWhiteSpace(name)) name = Path.GetFileNameWithoutExtension(processName);
                int sampleMs;
                string sampleError;
                if (!FrameScopeTargetEditRules.TryParseSampleInterval(Convert.ToString(row.Cells["SampleMs"].Value), out sampleMs, out sampleError))
                {
                    throw new InvalidOperationException("第 " + (row.Index + 1).ToString(CultureInfo.InvariantCulture) + " 行：" + sampleError);
                }
                targets.Add(new FrameScopeTarget
                {
                    Enabled = Convert.ToBoolean(row.Cells["Enabled"].Value ?? false),
                    Name = (name ?? processName).Trim(),
                    ProcessName = processName,
                    SampleIntervalMs = sampleMs,
                    OpenReportOnComplete = Convert.ToBoolean(row.Cells["AutoOpen"].Value ?? true)
                });
            }
        }

        FrameScopeConfig merged = FrameScopeConfigStore.BuildConfigFromEditableTargets(
            existing,
            dataRootText == null ? existing.DataRoot : dataRootText.Text,
            autoOpenCheck == null ? existing.OpenReportOnComplete : autoOpenCheck.Checked,
            targets);
        if (settingsSampleIntervalText != null)
        {
            int sampleMs;
            string sampleError;
            if (!FrameScopeTargetEditRules.TryParseSampleInterval(settingsSampleIntervalText.Text, out sampleMs, out sampleError))
            {
                throw new InvalidOperationException("采样间隔：" + sampleError);
            }
            foreach (FrameScopeTarget target in merged.Targets ?? new List<FrameScopeTarget>())
            {
                target.SampleIntervalMs = sampleMs;
                if (target.ProcessSampleIntervalMs < 100) target.ProcessSampleIntervalMs = 100;
                if (target.SlowSampleIntervalMs < sampleMs) target.SlowSampleIntervalMs = Math.Max(1000, sampleMs);
            }
        }
        merged.EnableVerboseLogs = verboseLogCheck == null ? existing.EnableVerboseLogs : verboseLogCheck.Checked;
        merged.EnablePerformanceDiagnosticsLogs = performanceDiagnosticsCheck == null ? existing.EnablePerformanceDiagnosticsLogs : performanceDiagnosticsCheck.Checked;
        merged.AutoGenerateDiagnosticReport = autoDiagnosticReportCheck == null ? existing.AutoGenerateDiagnosticReport : autoDiagnosticReportCheck.Checked;
        int retentionDays;
        if (!int.TryParse(logRetentionDaysText == null ? "" : logRetentionDaysText.Text, out retentionDays)) retentionDays = existing.LogRetentionDays;
        int maxLogMb;
        if (!int.TryParse(maxLogDiskMbText == null ? "" : maxLogDiskMbText.Text, out maxLogMb)) maxLogMb = existing.MaxLogDiskMb;
        merged.LogRetentionDays = retentionDays;
        merged.MaxLogDiskMb = maxLogMb;
        FrameScopeConfigStore.Normalize(merged);
        if (settingsSampleIntervalText != null && merged.Targets != null && merged.Targets.Count > 0) settingsSampleIntervalText.Text = merged.Targets[0].SampleIntervalMs.ToString(CultureInfo.InvariantCulture);
        if (logRetentionDaysText != null) logRetentionDaysText.Text = merged.LogRetentionDays.ToString(CultureInfo.InvariantCulture);
        if (maxLogDiskMbText != null) maxLogDiskMbText.Text = merged.MaxLogDiskMb.ToString(CultureInfo.InvariantCulture);
        return merged;
    }

    private static void SaveConfigFromGrid()
    {
        try
        {
            SetStatus("正在保存配置...");
            var saved = ReadGridConfig();
            SaveConfig(saved);
            var reloaded = LoadConfig();
            MarkPageCacheDirty("overview", "targets", "reports", "settings");
            if (string.Equals(activePageKey, "settings", StringComparison.OrdinalIgnoreCase) ||
                string.Equals(activePageKey, "targets", StringComparison.OrdinalIgnoreCase))
            {
                ShowPage(activePageKey);
            }
            if (targetCountLabel != null) targetCountLabel.Text = "已启用目标" + Environment.NewLine + EnabledTargetCount(reloaded).ToString(CultureInfo.InvariantCulture) + " 已启用";
            SetStatus("配置已保存并重新读取：" + ConfigPath);
        }
        catch (Exception ex)
        {
            SetStatus("配置保存失败：" + ex.Message);
            MessageBox.Show(ex.Message, "保存失败", MessageBoxButtons.OK, MessageBoxIcon.Error);
        }
    }

    private static void ResetConfigToDefaultsFromUi()
    {
        try
        {
            SetStatus("正在恢复默认配置...");
            var defaults = FrameScopeConfigStore.CreateDefaultConfig();
            SaveConfig(defaults);
            MarkPageCacheDirty("overview", "targets", "reports", "settings");
            if (targetCountLabel != null) targetCountLabel.Text = "已启用目标" + Environment.NewLine + EnabledTargetCount(defaults).ToString(CultureInfo.InvariantCulture) + " 已启用";
            SetStatus("已恢复默认配置并保存。");
            ShowPage("settings");
        }
        catch (Exception ex)
        {
            SetStatus("恢复默认配置失败：" + ex.Message);
            MessageBox.Show(ex.Message, "恢复默认失败", MessageBoxButtons.OK, MessageBoxIcon.Error);
        }
    }

    private static void BrowseDataRoot()
    {
        if (dataRootText == null)
        {
            ShowPage("settings");
            SetStatus("已打开“设置”页面，请在数据目录中选择路径。");
            return;
        }

        using (var dialog = new FolderBrowserDialog { Description = "选择 FrameScope 数据目录" })
        {
            if (dialog.ShowDialog(form) == DialogResult.OK)
            {
                dataRootText.Text = dialog.SelectedPath;
                SetConfigDirtyStatus();
            }
        }
    }
}
