using System;
using System.Collections.Generic;

public static class FrameScopeLoggingPolicy
{
    public static bool IsVerboseEnabled(FrameScopeConfig config)
    {
        return config != null && config.EnableVerboseLogs;
    }

    public static bool IsPerformanceDiagnosticsEnabled(FrameScopeConfig config)
    {
        return config != null && config.EnablePerformanceDiagnosticsLogs;
    }

    public static bool ShouldAutoGenerateDiagnosticReport(Dictionary<string, object> status, int monitorExitCode)
    {
        if (monitorExitCode != 0) return true;
        if (status == null || status.Count == 0) return true;

        string phase = ReadString(status, "Phase");
        if (phase.Equals("error", StringComparison.OrdinalIgnoreCase) ||
            phase.Equals("timeout-waiting-for-target", StringComparison.OrdinalIgnoreCase))
        {
            return true;
        }

        if (!string.IsNullOrWhiteSpace(ReadString(status, "ReportError"))) return true;

        string reportKind = ReadString(status, "ReportKind");
        if (reportKind.Equals("diagnostic", StringComparison.OrdinalIgnoreCase)) return true;

        string frameCaptureStatus = ReadString(status, "FrameCaptureStatus");
        if (!string.IsNullOrWhiteSpace(frameCaptureStatus) &&
            !frameCaptureStatus.Equals("captured", StringComparison.OrdinalIgnoreCase))
        {
            return true;
        }

        int reportFrameCount = ReadInt(status, "ReportFrameCount", -1);
        bool reportHasFrameData = ReadBool(status, "ReportHasFrameData", reportFrameCount > 0);
        if (reportKind.Equals("full", StringComparison.OrdinalIgnoreCase) && reportHasFrameData)
        {
            return false;
        }

        return false;
    }

    private static string ReadString(Dictionary<string, object> status, string key)
    {
        object value;
        return status != null && status.TryGetValue(key, out value) && value != null
            ? Convert.ToString(value)
            : "";
    }

    private static int ReadInt(Dictionary<string, object> status, string key, int fallback)
    {
        object value;
        if (status != null && status.TryGetValue(key, out value) && value != null)
        {
            try { return Convert.ToInt32(value); }
            catch { }
        }
        return fallback;
    }

    private static bool ReadBool(Dictionary<string, object> status, string key, bool fallback)
    {
        object value;
        if (status != null && status.TryGetValue(key, out value) && value != null)
        {
            try { return Convert.ToBoolean(value); }
            catch { }
        }
        return fallback;
    }
}

public sealed class FrameScopeLogRateLimiter
{
    private readonly object gate = new object();
    private readonly Dictionary<string, FrameScopeLogRateLimitState> states = new Dictionary<string, FrameScopeLogRateLimitState>(StringComparer.OrdinalIgnoreCase);

    public bool ShouldWrite(string key, string state, DateTime nowUtc, TimeSpan minInterval)
    {
        if (string.IsNullOrWhiteSpace(key)) return true;
        if (minInterval <= TimeSpan.Zero) return true;

        string currentState = state ?? "";
        lock (gate)
        {
            FrameScopeLogRateLimitState previous;
            if (!states.TryGetValue(key, out previous))
            {
                states[key] = new FrameScopeLogRateLimitState(currentState, nowUtc);
                return true;
            }

            if (!string.Equals(previous.State, currentState, StringComparison.Ordinal))
            {
                states[key] = new FrameScopeLogRateLimitState(currentState, nowUtc);
                return true;
            }

            if (nowUtc - previous.LastWriteUtc >= minInterval)
            {
                states[key] = new FrameScopeLogRateLimitState(currentState, nowUtc);
                return true;
            }

            return false;
        }
    }

    private sealed class FrameScopeLogRateLimitState
    {
        public FrameScopeLogRateLimitState(string state, DateTime lastWriteUtc)
        {
            State = state ?? "";
            LastWriteUtc = lastWriteUtc;
        }

        public string State { get; private set; }
        public DateTime LastWriteUtc { get; private set; }
    }
}
