using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web.Script.Serialization;

public static class FrameScopeConfigStore
{
    public const string NativeMonitorMode = "native-csharp";

    private static readonly JavaScriptSerializer Json = new JavaScriptSerializer { MaxJsonLength = int.MaxValue };

    public static string DefaultDataRoot
    {
        get
        {
            return Path.Combine(
                Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),
                "FrameScopeMonitorData",
                "framescope-runs");
        }
    }

    public static FrameScopeConfig CreateDefaultConfig()
    {
        return new FrameScopeConfig
        {
            PollIntervalMs = 1000,
            DataRoot = DefaultDataRoot,
            OpenReportOnComplete = true,
            EnableVerboseLogs = false,
            EnablePerformanceDiagnosticsLogs = false,
            AutoGenerateDiagnosticReport = false,
            LogRetentionDays = 14,
            MaxLogDiskMb = 100,
            MonitorScript = NativeMonitorMode,
            Targets = new List<FrameScopeTarget>
            {
                Target(true, "Counter-Strike 2", "cs2.exe"),
                Target(true, "PUBG: BATTLEGROUNDS", "TslGame.exe"),
                Target(true, "Delta Force", "DeltaForceClient-Win64-Shipping.exe"),
                Target(true, "Neverness To Everness", "HTGame.exe"),
                Target(false, "Valorant", "VALORANT-Win64-Shipping.exe"),
                Target(false, "Cyberpunk 2077", "Cyberpunk2077.exe"),
                Target(false, "Battlefield 6", "bf6.exe"),
                Target(false, "Hogwarts Legacy", "HogwartsLegacy.exe"),
                Target(false, "OPUS Prism Peak", "OPUS_ Prism Peak.exe")
            }
        };
    }

    public static FrameScopeConfig Load(string path)
    {
        if (string.IsNullOrWhiteSpace(path)) throw new ArgumentException("Config path is empty.", "path");
        if (!File.Exists(path))
        {
            FrameScopeConfig created = CreateDefaultConfig();
            Save(path, created);
            return created;
        }

        try
        {
            FrameScopeConfig config = Json.Deserialize<FrameScopeConfig>(File.ReadAllText(path));
            Normalize(config);
            return config;
        }
        catch
        {
            return CreateDefaultConfig();
        }
    }

    public static void Save(string path, FrameScopeConfig config)
    {
        if (string.IsNullOrWhiteSpace(path)) throw new ArgumentException("Config path is empty.", "path");
        Normalize(config);
        string dir = Path.GetDirectoryName(Path.GetFullPath(path));
        if (!string.IsNullOrEmpty(dir)) Directory.CreateDirectory(dir);
        File.WriteAllText(path, Json.Serialize(config));
    }

    public static void Normalize(FrameScopeConfig config)
    {
        if (config == null) throw new InvalidOperationException("FrameScope config is empty.");
        if (config.Targets == null) config.Targets = new List<FrameScopeTarget>();
        if (string.IsNullOrWhiteSpace(config.DataRoot)) config.DataRoot = DefaultDataRoot;
        if (string.IsNullOrWhiteSpace(config.MonitorScript) ||
            config.MonitorScript.EndsWith(".ps1", StringComparison.OrdinalIgnoreCase))
        {
            config.MonitorScript = NativeMonitorMode;
        }
        if (config.PollIntervalMs <= 0) config.PollIntervalMs = 1000;
        if (config.LogRetentionDays <= 0) config.LogRetentionDays = 14;
        if (config.LogRetentionDays > 365) config.LogRetentionDays = 365;
        if (config.MaxLogDiskMb <= 0) config.MaxLogDiskMb = 100;
        if (config.MaxLogDiskMb > 2048) config.MaxLogDiskMb = 2048;
        foreach (FrameScopeTarget target in config.Targets)
        {
            NormalizeTarget(target);
        }
    }

    public static FrameScopeConfig BuildConfigFromEditableTargets(FrameScopeConfig existing, string dataRoot, bool openReportOnComplete, IEnumerable<FrameScopeTarget> editableTargets)
    {
        if (existing == null) existing = CreateDefaultConfig();
        Normalize(existing);

        List<FrameScopeTarget> targets = new List<FrameScopeTarget>();
        foreach (FrameScopeTarget editable in editableTargets ?? Enumerable.Empty<FrameScopeTarget>())
        {
            if (editable == null) continue;
            string processName = (editable.ProcessName ?? "").Trim();
            if (string.IsNullOrWhiteSpace(processName)) continue;

            string name = string.IsNullOrWhiteSpace(editable.Name)
                ? Path.GetFileNameWithoutExtension(processName)
                : editable.Name.Trim();
            int sampleMs = editable.SampleIntervalMs >= 50 ? editable.SampleIntervalMs : 100;
            FrameScopeTarget preserved = FindExistingTarget(existing, processName, name);

            int processSampleMs = preserved != null && preserved.ProcessSampleIntervalMs >= 100
                ? preserved.ProcessSampleIntervalMs
                : Math.Max(100, editable.ProcessSampleIntervalMs);
            int slowSampleMs = preserved != null && preserved.SlowSampleIntervalMs >= sampleMs
                ? preserved.SlowSampleIntervalMs
                : (editable.SlowSampleIntervalMs >= sampleMs ? editable.SlowSampleIntervalMs : Math.Max(1000, sampleMs));

            targets.Add(new FrameScopeTarget
            {
                Enabled = editable.Enabled,
                Name = name ?? processName,
                ProcessName = processName,
                SampleIntervalMs = sampleMs,
                ProcessSampleIntervalMs = processSampleMs,
                SlowSampleIntervalMs = slowSampleMs,
                OpenReportOnComplete = editable.OpenReportOnComplete
            });
        }

        FrameScopeConfig merged = new FrameScopeConfig
        {
            PollIntervalMs = existing.PollIntervalMs > 0 ? existing.PollIntervalMs : 1000,
            DataRoot = (dataRoot ?? "").Trim(),
            OpenReportOnComplete = openReportOnComplete,
            EnableVerboseLogs = existing.EnableVerboseLogs,
            EnablePerformanceDiagnosticsLogs = existing.EnablePerformanceDiagnosticsLogs,
            AutoGenerateDiagnosticReport = existing.AutoGenerateDiagnosticReport,
            LogRetentionDays = existing.LogRetentionDays,
            MaxLogDiskMb = existing.MaxLogDiskMb,
            MonitorScript = NativeMonitorMode,
            Targets = targets
        };
        Normalize(merged);
        return merged;
    }

    public static FrameScopeTarget FindExistingTarget(FrameScopeConfig config, string processName, string name)
    {
        if (config == null || config.Targets == null) return null;
        string processBase = GetTargetBaseName(processName);
        foreach (FrameScopeTarget target in config.Targets)
        {
            if (target == null || string.IsNullOrWhiteSpace(target.ProcessName)) continue;
            if (target.ProcessName.Equals(processName, StringComparison.OrdinalIgnoreCase)) return target;
        }
        foreach (FrameScopeTarget target in config.Targets)
        {
            if (target == null || string.IsNullOrWhiteSpace(target.ProcessName)) continue;
            if (GetTargetBaseName(target.ProcessName).Equals(processBase, StringComparison.OrdinalIgnoreCase)) return target;
        }
        foreach (FrameScopeTarget target in config.Targets)
        {
            if (target == null || string.IsNullOrWhiteSpace(target.Name) || string.IsNullOrWhiteSpace(name)) continue;
            if (target.Name.Equals(name, StringComparison.OrdinalIgnoreCase)) return target;
        }
        return null;
    }

    private static FrameScopeTarget Target(bool enabled, string name, string processName)
    {
        return new FrameScopeTarget
        {
            Enabled = enabled,
            Name = name,
            ProcessName = processName,
            SampleIntervalMs = 100,
            ProcessSampleIntervalMs = 100,
            SlowSampleIntervalMs = 1000,
            OpenReportOnComplete = true
        };
    }

    private static void NormalizeTarget(FrameScopeTarget target)
    {
        if (target == null) return;
        if (target.SampleIntervalMs < 50) target.SampleIntervalMs = 100;
        if (target.ProcessSampleIntervalMs < 100) target.ProcessSampleIntervalMs = 100;
        if (target.SlowSampleIntervalMs < target.SampleIntervalMs) target.SlowSampleIntervalMs = Math.Max(1000, target.SampleIntervalMs);
    }

    private static string GetTargetBaseName(string processName)
    {
        if (string.IsNullOrWhiteSpace(processName)) return "";
        try { return Path.GetFileNameWithoutExtension(processName.Trim()); }
        catch { return processName.Trim(); }
    }
}

public sealed class FrameScopeConfig
{
    public FrameScopeConfig()
    {
        PollIntervalMs = 1000;
        DataRoot = "";
        OpenReportOnComplete = true;
        EnableVerboseLogs = false;
        EnablePerformanceDiagnosticsLogs = false;
        AutoGenerateDiagnosticReport = false;
        LogRetentionDays = 14;
        MaxLogDiskMb = 100;
        MonitorScript = "";
        Targets = new List<FrameScopeTarget>();
    }

    public int PollIntervalMs { get; set; }
    public string DataRoot { get; set; }
    public bool OpenReportOnComplete { get; set; }
    public bool EnableVerboseLogs { get; set; }
    public bool EnablePerformanceDiagnosticsLogs { get; set; }
    public bool AutoGenerateDiagnosticReport { get; set; }
    public int LogRetentionDays { get; set; }
    public int MaxLogDiskMb { get; set; }
    public string MonitorScript { get; set; }
    public List<FrameScopeTarget> Targets { get; set; }
}

public sealed class FrameScopeTarget
{
    public FrameScopeTarget()
    {
        Name = "";
        ProcessName = "";
        SampleIntervalMs = 100;
        ProcessSampleIntervalMs = 100;
        SlowSampleIntervalMs = 1000;
        OpenReportOnComplete = true;
    }

    public bool Enabled { get; set; }
    public string Name { get; set; }
    public string ProcessName { get; set; }
    public int SampleIntervalMs { get; set; }
    public int ProcessSampleIntervalMs { get; set; }
    public int SlowSampleIntervalMs { get; set; }
    public bool OpenReportOnComplete { get; set; }
}
